// Code generated by protoc-gen-go. DO NOT EDIT.
// source: juxuny_yc_dt_base.proto

package dt // import "github.com/juxuny/yc/dt"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ID struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid" json:"valid,omitempty"`
	Uint64               uint64   `protobuf:"varint,2,opt,name=uint64" json:"uint64,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_juxuny_yc_dt_base_eb3fc12e9d4d2839, []int{0}
}
func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (dst *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(dst, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *ID) GetUint64() uint64 {
	if m != nil {
		return m.Uint64
	}
	return 0
}

type NullString struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid" json:"valid,omitempty"`
	String_              string   `protobuf:"bytes,2,opt,name=string" json:"string,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *NullString) Reset()         { *m = NullString{} }
func (m *NullString) String() string { return proto.CompactTextString(m) }
func (*NullString) ProtoMessage()    {}
func (*NullString) Descriptor() ([]byte, []int) {
	return fileDescriptor_juxuny_yc_dt_base_eb3fc12e9d4d2839, []int{1}
}
func (m *NullString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullString.Unmarshal(m, b)
}
func (m *NullString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullString.Marshal(b, m, deterministic)
}
func (dst *NullString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullString.Merge(dst, src)
}
func (m *NullString) XXX_Size() int {
	return xxx_messageInfo_NullString.Size(m)
}
func (m *NullString) XXX_DiscardUnknown() {
	xxx_messageInfo_NullString.DiscardUnknown(m)
}

var xxx_messageInfo_NullString proto.InternalMessageInfo

func (m *NullString) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *NullString) GetString_() string {
	if m != nil {
		return m.String_
	}
	return ""
}

type NullInt64 struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid" json:"valid,omitempty"`
	Int64                int64    `protobuf:"varint,2,opt,name=int64" json:"int64,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *NullInt64) Reset()         { *m = NullInt64{} }
func (m *NullInt64) String() string { return proto.CompactTextString(m) }
func (*NullInt64) ProtoMessage()    {}
func (*NullInt64) Descriptor() ([]byte, []int) {
	return fileDescriptor_juxuny_yc_dt_base_eb3fc12e9d4d2839, []int{2}
}
func (m *NullInt64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullInt64.Unmarshal(m, b)
}
func (m *NullInt64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullInt64.Marshal(b, m, deterministic)
}
func (dst *NullInt64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullInt64.Merge(dst, src)
}
func (m *NullInt64) XXX_Size() int {
	return xxx_messageInfo_NullInt64.Size(m)
}
func (m *NullInt64) XXX_DiscardUnknown() {
	xxx_messageInfo_NullInt64.DiscardUnknown(m)
}

var xxx_messageInfo_NullInt64 proto.InternalMessageInfo

func (m *NullInt64) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *NullInt64) GetInt64() int64 {
	if m != nil {
		return m.Int64
	}
	return 0
}

type NullInt32 struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid" json:"valid,omitempty"`
	Int32                int32    `protobuf:"varint,2,opt,name=int32" json:"int32,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *NullInt32) Reset()         { *m = NullInt32{} }
func (m *NullInt32) String() string { return proto.CompactTextString(m) }
func (*NullInt32) ProtoMessage()    {}
func (*NullInt32) Descriptor() ([]byte, []int) {
	return fileDescriptor_juxuny_yc_dt_base_eb3fc12e9d4d2839, []int{3}
}
func (m *NullInt32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullInt32.Unmarshal(m, b)
}
func (m *NullInt32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullInt32.Marshal(b, m, deterministic)
}
func (dst *NullInt32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullInt32.Merge(dst, src)
}
func (m *NullInt32) XXX_Size() int {
	return xxx_messageInfo_NullInt32.Size(m)
}
func (m *NullInt32) XXX_DiscardUnknown() {
	xxx_messageInfo_NullInt32.DiscardUnknown(m)
}

var xxx_messageInfo_NullInt32 proto.InternalMessageInfo

func (m *NullInt32) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *NullInt32) GetInt32() int32 {
	if m != nil {
		return m.Int32
	}
	return 0
}

type NullBool struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid" json:"valid,omitempty"`
	Bool                 bool     `protobuf:"varint,2,opt,name=bool" json:"bool,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *NullBool) Reset()         { *m = NullBool{} }
func (m *NullBool) String() string { return proto.CompactTextString(m) }
func (*NullBool) ProtoMessage()    {}
func (*NullBool) Descriptor() ([]byte, []int) {
	return fileDescriptor_juxuny_yc_dt_base_eb3fc12e9d4d2839, []int{4}
}
func (m *NullBool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullBool.Unmarshal(m, b)
}
func (m *NullBool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullBool.Marshal(b, m, deterministic)
}
func (dst *NullBool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullBool.Merge(dst, src)
}
func (m *NullBool) XXX_Size() int {
	return xxx_messageInfo_NullBool.Size(m)
}
func (m *NullBool) XXX_DiscardUnknown() {
	xxx_messageInfo_NullBool.DiscardUnknown(m)
}

var xxx_messageInfo_NullBool proto.InternalMessageInfo

func (m *NullBool) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *NullBool) GetBool() bool {
	if m != nil {
		return m.Bool
	}
	return false
}

type NullFloat64 struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid" json:"valid,omitempty"`
	Float64              float64  `protobuf:"fixed64,2,opt,name=float64" json:"float64,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *NullFloat64) Reset()         { *m = NullFloat64{} }
func (m *NullFloat64) String() string { return proto.CompactTextString(m) }
func (*NullFloat64) ProtoMessage()    {}
func (*NullFloat64) Descriptor() ([]byte, []int) {
	return fileDescriptor_juxuny_yc_dt_base_eb3fc12e9d4d2839, []int{5}
}
func (m *NullFloat64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullFloat64.Unmarshal(m, b)
}
func (m *NullFloat64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullFloat64.Marshal(b, m, deterministic)
}
func (dst *NullFloat64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullFloat64.Merge(dst, src)
}
func (m *NullFloat64) XXX_Size() int {
	return xxx_messageInfo_NullFloat64.Size(m)
}
func (m *NullFloat64) XXX_DiscardUnknown() {
	xxx_messageInfo_NullFloat64.DiscardUnknown(m)
}

var xxx_messageInfo_NullFloat64 proto.InternalMessageInfo

func (m *NullFloat64) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *NullFloat64) GetFloat64() float64 {
	if m != nil {
		return m.Float64
	}
	return 0
}

type NullFloat32 struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid" json:"valid,omitempty"`
	Float32              float32  `protobuf:"fixed32,2,opt,name=float32" json:"float32,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *NullFloat32) Reset()         { *m = NullFloat32{} }
func (m *NullFloat32) String() string { return proto.CompactTextString(m) }
func (*NullFloat32) ProtoMessage()    {}
func (*NullFloat32) Descriptor() ([]byte, []int) {
	return fileDescriptor_juxuny_yc_dt_base_eb3fc12e9d4d2839, []int{6}
}
func (m *NullFloat32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullFloat32.Unmarshal(m, b)
}
func (m *NullFloat32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullFloat32.Marshal(b, m, deterministic)
}
func (dst *NullFloat32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullFloat32.Merge(dst, src)
}
func (m *NullFloat32) XXX_Size() int {
	return xxx_messageInfo_NullFloat32.Size(m)
}
func (m *NullFloat32) XXX_DiscardUnknown() {
	xxx_messageInfo_NullFloat32.DiscardUnknown(m)
}

var xxx_messageInfo_NullFloat32 proto.InternalMessageInfo

func (m *NullFloat32) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *NullFloat32) GetFloat32() float32 {
	if m != nil {
		return m.Float32
	}
	return 0
}

type Pagination struct {
	PageNum              int64    `protobuf:"varint,1,opt,name=pageNum" json:"pageNum,omitempty"`
	PageSize             int64    `protobuf:"varint,2,opt,name=pageSize" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Pagination) Reset()         { *m = Pagination{} }
func (m *Pagination) String() string { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()    {}
func (*Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_juxuny_yc_dt_base_eb3fc12e9d4d2839, []int{7}
}
func (m *Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pagination.Unmarshal(m, b)
}
func (m *Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pagination.Marshal(b, m, deterministic)
}
func (dst *Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pagination.Merge(dst, src)
}
func (m *Pagination) XXX_Size() int {
	return xxx_messageInfo_Pagination.Size(m)
}
func (m *Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_Pagination proto.InternalMessageInfo

func (m *Pagination) GetPageNum() int64 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *Pagination) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type PaginationResp struct {
	PageNum              int64    `protobuf:"varint,1,opt,name=pageNum" json:"pageNum,omitempty"`
	PageSize             int64    `protobuf:"varint,2,opt,name=pageSize" json:"pageSize,omitempty"`
	Total                int64    `protobuf:"varint,3,opt,name=total" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *PaginationResp) Reset()         { *m = PaginationResp{} }
func (m *PaginationResp) String() string { return proto.CompactTextString(m) }
func (*PaginationResp) ProtoMessage()    {}
func (*PaginationResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_juxuny_yc_dt_base_eb3fc12e9d4d2839, []int{8}
}
func (m *PaginationResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaginationResp.Unmarshal(m, b)
}
func (m *PaginationResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaginationResp.Marshal(b, m, deterministic)
}
func (dst *PaginationResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaginationResp.Merge(dst, src)
}
func (m *PaginationResp) XXX_Size() int {
	return xxx_messageInfo_PaginationResp.Size(m)
}
func (m *PaginationResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PaginationResp.DiscardUnknown(m)
}

var xxx_messageInfo_PaginationResp proto.InternalMessageInfo

func (m *PaginationResp) GetPageNum() int64 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *PaginationResp) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PaginationResp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*ID)(nil), "dt.ID")
	proto.RegisterType((*NullString)(nil), "dt.NullString")
	proto.RegisterType((*NullInt64)(nil), "dt.NullInt64")
	proto.RegisterType((*NullInt32)(nil), "dt.NullInt32")
	proto.RegisterType((*NullBool)(nil), "dt.NullBool")
	proto.RegisterType((*NullFloat64)(nil), "dt.NullFloat64")
	proto.RegisterType((*NullFloat32)(nil), "dt.NullFloat32")
	proto.RegisterType((*Pagination)(nil), "dt.Pagination")
	proto.RegisterType((*PaginationResp)(nil), "dt.PaginationResp")
}

func init() {
	proto.RegisterFile("juxuny_yc_dt_base.proto", fileDescriptor_juxuny_yc_dt_base_eb3fc12e9d4d2839)
}

var fileDescriptor_juxuny_yc_dt_base_eb3fc12e9d4d2839 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcf, 0x4b, 0xf3, 0x30,
	0x18, 0xc7, 0x69, 0xbb, 0xee, 0xed, 0x9e, 0x17, 0x3c, 0x94, 0xe1, 0xaa, 0xa7, 0x91, 0xd3, 0x4e,
	0x2b, 0xb4, 0x43, 0x41, 0xf0, 0x52, 0x44, 0xd8, 0x65, 0x48, 0x76, 0x13, 0xa1, 0xa4, 0x3f, 0xac,
	0x91, 0xac, 0x29, 0x6b, 0x22, 0xd6, 0xbf, 0x5e, 0x92, 0xb4, 0x4e, 0x0f, 0xf5, 0xe0, 0xed, 0xf9,
	0x90, 0xe7, 0xf3, 0xe4, 0x4b, 0xf2, 0xc0, 0xe2, 0x55, 0xbe, 0xcb, 0xba, 0x4b, 0xbb, 0x3c, 0x2d,
	0x44, 0x9a, 0x91, 0xb6, 0x5c, 0x37, 0x47, 0x2e, 0xb8, 0x6f, 0x17, 0x02, 0x45, 0x60, 0x6f, 0xef,
	0xfc, 0x39, 0xb8, 0x6f, 0x84, 0xd1, 0x22, 0xb0, 0x96, 0xd6, 0xca, 0xc3, 0x06, 0xfc, 0x73, 0x98,
	0x4a, 0x5a, 0x8b, 0xab, 0x4d, 0x60, 0x2f, 0xad, 0xd5, 0x04, 0xf7, 0x84, 0x6e, 0x00, 0x76, 0x92,
	0xb1, 0xbd, 0x38, 0xd2, 0xba, 0x1a, 0x77, 0x5b, 0x7d, 0xae, 0xdd, 0x19, 0xee, 0x09, 0x5d, 0xc3,
	0x4c, 0xb9, 0x5b, 0x35, 0x68, 0x44, 0x9d, 0x83, 0x7b, 0xba, 0xd5, 0xc1, 0x06, 0xbe, 0x89, 0x71,
	0xf4, 0xab, 0x18, 0x47, 0x5a, 0x74, 0xb1, 0x01, 0xb4, 0x01, 0x4f, 0x89, 0x09, 0xe7, 0x6c, 0xc4,
	0xf3, 0x61, 0x92, 0x71, 0xce, 0xb4, 0xe6, 0x61, 0x5d, 0xa3, 0x5b, 0xf8, 0xaf, 0xac, 0x7b, 0xc6,
	0xc9, 0x78, 0xd2, 0x00, 0xfe, 0x3d, 0x9b, 0x06, 0xed, 0x5a, 0x78, 0xc0, 0x1f, 0xfa, 0x68, 0xde,
	0x41, 0xef, 0x13, 0xdb, 0x78, 0x40, 0x94, 0x00, 0x3c, 0x90, 0x8a, 0xd6, 0x44, 0x50, 0x5e, 0xab,
	0xbe, 0x86, 0x54, 0xe5, 0x4e, 0x1e, 0xb4, 0xef, 0xe0, 0x01, 0xfd, 0x4b, 0xf0, 0x54, 0xb9, 0xa7,
	0x1f, 0x65, 0xff, 0x5a, 0x5f, 0x8c, 0x9e, 0xe0, 0xec, 0x34, 0x03, 0x97, 0x6d, 0xf3, 0xb7, 0x39,
	0x2a, 0xbb, 0xe0, 0x82, 0xb0, 0xc0, 0x31, 0xdf, 0xa1, 0x21, 0xb9, 0x78, 0x5c, 0x54, 0x54, 0xbc,
	0xc8, 0x6c, 0x9d, 0xf3, 0x43, 0x68, 0x36, 0x2c, 0xec, 0xf2, 0xb0, 0x10, 0xd9, 0x54, 0x6f, 0x57,
	0xfc, 0x19, 0x00, 0x00, 0xff, 0xff, 0x18, 0xb6, 0x46, 0x91, 0x78, 0x02, 0x00, 0x00,
}
