// Code generated by protoc-gen-go. DO NOT EDIT.
// source: juxuny_yc_dt_base.proto

package dt // import "github.com/juxuny/yc/dt"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ID struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid" json:"valid,omitempty"`
	Uint64               uint64   `protobuf:"varint,2,opt,name=uint64" json:"uint64,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_juxuny_yc_dt_base_b12c8401f315b5f7, []int{0}
}
func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (dst *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(dst, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *ID) GetUint64() uint64 {
	if m != nil {
		return m.Uint64
	}
	return 0
}

type NullString struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid" json:"valid,omitempty"`
	String_              string   `protobuf:"bytes,2,opt,name=string" json:"string,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *NullString) Reset()         { *m = NullString{} }
func (m *NullString) String() string { return proto.CompactTextString(m) }
func (*NullString) ProtoMessage()    {}
func (*NullString) Descriptor() ([]byte, []int) {
	return fileDescriptor_juxuny_yc_dt_base_b12c8401f315b5f7, []int{1}
}
func (m *NullString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullString.Unmarshal(m, b)
}
func (m *NullString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullString.Marshal(b, m, deterministic)
}
func (dst *NullString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullString.Merge(dst, src)
}
func (m *NullString) XXX_Size() int {
	return xxx_messageInfo_NullString.Size(m)
}
func (m *NullString) XXX_DiscardUnknown() {
	xxx_messageInfo_NullString.DiscardUnknown(m)
}

var xxx_messageInfo_NullString proto.InternalMessageInfo

func (m *NullString) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *NullString) GetString_() string {
	if m != nil {
		return m.String_
	}
	return ""
}

type NullInt64 struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid" json:"valid,omitempty"`
	Int64                int64    `protobuf:"varint,2,opt,name=int64" json:"int64,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *NullInt64) Reset()         { *m = NullInt64{} }
func (m *NullInt64) String() string { return proto.CompactTextString(m) }
func (*NullInt64) ProtoMessage()    {}
func (*NullInt64) Descriptor() ([]byte, []int) {
	return fileDescriptor_juxuny_yc_dt_base_b12c8401f315b5f7, []int{2}
}
func (m *NullInt64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullInt64.Unmarshal(m, b)
}
func (m *NullInt64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullInt64.Marshal(b, m, deterministic)
}
func (dst *NullInt64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullInt64.Merge(dst, src)
}
func (m *NullInt64) XXX_Size() int {
	return xxx_messageInfo_NullInt64.Size(m)
}
func (m *NullInt64) XXX_DiscardUnknown() {
	xxx_messageInfo_NullInt64.DiscardUnknown(m)
}

var xxx_messageInfo_NullInt64 proto.InternalMessageInfo

func (m *NullInt64) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *NullInt64) GetInt64() int64 {
	if m != nil {
		return m.Int64
	}
	return 0
}

type NullInt32 struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid" json:"valid,omitempty"`
	Int32                int32    `protobuf:"varint,2,opt,name=int32" json:"int32,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *NullInt32) Reset()         { *m = NullInt32{} }
func (m *NullInt32) String() string { return proto.CompactTextString(m) }
func (*NullInt32) ProtoMessage()    {}
func (*NullInt32) Descriptor() ([]byte, []int) {
	return fileDescriptor_juxuny_yc_dt_base_b12c8401f315b5f7, []int{3}
}
func (m *NullInt32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullInt32.Unmarshal(m, b)
}
func (m *NullInt32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullInt32.Marshal(b, m, deterministic)
}
func (dst *NullInt32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullInt32.Merge(dst, src)
}
func (m *NullInt32) XXX_Size() int {
	return xxx_messageInfo_NullInt32.Size(m)
}
func (m *NullInt32) XXX_DiscardUnknown() {
	xxx_messageInfo_NullInt32.DiscardUnknown(m)
}

var xxx_messageInfo_NullInt32 proto.InternalMessageInfo

func (m *NullInt32) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *NullInt32) GetInt32() int32 {
	if m != nil {
		return m.Int32
	}
	return 0
}

type NullBool struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid" json:"valid,omitempty"`
	Bool                 bool     `protobuf:"varint,2,opt,name=bool" json:"bool,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *NullBool) Reset()         { *m = NullBool{} }
func (m *NullBool) String() string { return proto.CompactTextString(m) }
func (*NullBool) ProtoMessage()    {}
func (*NullBool) Descriptor() ([]byte, []int) {
	return fileDescriptor_juxuny_yc_dt_base_b12c8401f315b5f7, []int{4}
}
func (m *NullBool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullBool.Unmarshal(m, b)
}
func (m *NullBool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullBool.Marshal(b, m, deterministic)
}
func (dst *NullBool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullBool.Merge(dst, src)
}
func (m *NullBool) XXX_Size() int {
	return xxx_messageInfo_NullBool.Size(m)
}
func (m *NullBool) XXX_DiscardUnknown() {
	xxx_messageInfo_NullBool.DiscardUnknown(m)
}

var xxx_messageInfo_NullBool proto.InternalMessageInfo

func (m *NullBool) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *NullBool) GetBool() bool {
	if m != nil {
		return m.Bool
	}
	return false
}

type NullFloat64 struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid" json:"valid,omitempty"`
	Float64              float64  `protobuf:"fixed64,2,opt,name=float64" json:"float64,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *NullFloat64) Reset()         { *m = NullFloat64{} }
func (m *NullFloat64) String() string { return proto.CompactTextString(m) }
func (*NullFloat64) ProtoMessage()    {}
func (*NullFloat64) Descriptor() ([]byte, []int) {
	return fileDescriptor_juxuny_yc_dt_base_b12c8401f315b5f7, []int{5}
}
func (m *NullFloat64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullFloat64.Unmarshal(m, b)
}
func (m *NullFloat64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullFloat64.Marshal(b, m, deterministic)
}
func (dst *NullFloat64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullFloat64.Merge(dst, src)
}
func (m *NullFloat64) XXX_Size() int {
	return xxx_messageInfo_NullFloat64.Size(m)
}
func (m *NullFloat64) XXX_DiscardUnknown() {
	xxx_messageInfo_NullFloat64.DiscardUnknown(m)
}

var xxx_messageInfo_NullFloat64 proto.InternalMessageInfo

func (m *NullFloat64) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *NullFloat64) GetFloat64() float64 {
	if m != nil {
		return m.Float64
	}
	return 0
}

type NullFloat32 struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid" json:"valid,omitempty"`
	Float32              float32  `protobuf:"fixed32,2,opt,name=float32" json:"float32,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *NullFloat32) Reset()         { *m = NullFloat32{} }
func (m *NullFloat32) String() string { return proto.CompactTextString(m) }
func (*NullFloat32) ProtoMessage()    {}
func (*NullFloat32) Descriptor() ([]byte, []int) {
	return fileDescriptor_juxuny_yc_dt_base_b12c8401f315b5f7, []int{6}
}
func (m *NullFloat32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullFloat32.Unmarshal(m, b)
}
func (m *NullFloat32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullFloat32.Marshal(b, m, deterministic)
}
func (dst *NullFloat32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullFloat32.Merge(dst, src)
}
func (m *NullFloat32) XXX_Size() int {
	return xxx_messageInfo_NullFloat32.Size(m)
}
func (m *NullFloat32) XXX_DiscardUnknown() {
	xxx_messageInfo_NullFloat32.DiscardUnknown(m)
}

var xxx_messageInfo_NullFloat32 proto.InternalMessageInfo

func (m *NullFloat32) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *NullFloat32) GetFloat32() float32 {
	if m != nil {
		return m.Float32
	}
	return 0
}

func init() {
	proto.RegisterType((*ID)(nil), "dt.ID")
	proto.RegisterType((*NullString)(nil), "dt.NullString")
	proto.RegisterType((*NullInt64)(nil), "dt.NullInt64")
	proto.RegisterType((*NullInt32)(nil), "dt.NullInt32")
	proto.RegisterType((*NullBool)(nil), "dt.NullBool")
	proto.RegisterType((*NullFloat64)(nil), "dt.NullFloat64")
	proto.RegisterType((*NullFloat32)(nil), "dt.NullFloat32")
}

func init() {
	proto.RegisterFile("juxuny_yc_dt_base.proto", fileDescriptor_juxuny_yc_dt_base_b12c8401f315b5f7)
}

var fileDescriptor_juxuny_yc_dt_base_b12c8401f315b5f7 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0xd1, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc0, 0x71, 0x5a, 0xd7, 0xd9, 0x3d, 0x6f, 0x65, 0xb8, 0x7a, 0x1b, 0x39, 0xed, 0xb4, 0x42,
	0x3b, 0x14, 0x04, 0x2f, 0x43, 0x84, 0x5d, 0x3c, 0x3c, 0x6f, 0x5e, 0x4a, 0xd3, 0xe8, 0x8c, 0xc4,
	0x3e, 0xd9, 0x12, 0xb1, 0xdf, 0x5e, 0x92, 0xb4, 0xa8, 0x87, 0xec, 0xd6, 0x3f, 0xcd, 0x2f, 0x79,
	0xf0, 0x60, 0xf1, 0x6e, 0xbe, 0x4d, 0xd7, 0xd7, 0x7d, 0x5b, 0x0b, 0x5d, 0xf3, 0xe6, 0xf8, 0xb2,
	0xfe, 0x3c, 0x90, 0xa6, 0x2c, 0x16, 0x9a, 0x95, 0x10, 0xef, 0xee, 0xb3, 0x39, 0x24, 0x5f, 0x8d,
	0x92, 0x22, 0x8f, 0x96, 0xd1, 0x2a, 0x45, 0x1f, 0xd9, 0x25, 0x4c, 0x8d, 0xec, 0xf4, 0xf5, 0x26,
	0x8f, 0x97, 0xd1, 0x6a, 0x82, 0x43, 0xb1, 0x5b, 0x80, 0x47, 0xa3, 0xd4, 0x93, 0x3e, 0xc8, 0x6e,
	0x1f, 0xb6, 0x47, 0xf7, 0xdf, 0xd9, 0x19, 0x0e, 0xc5, 0x6e, 0x60, 0x66, 0xed, 0xce, 0x5e, 0x14,
	0xa0, 0x73, 0x48, 0x7e, 0x5f, 0x3d, 0x43, 0x1f, 0x7f, 0x60, 0x55, 0x9e, 0x84, 0x55, 0xe9, 0x60,
	0x82, 0x3e, 0xd8, 0x06, 0x52, 0x0b, 0xb7, 0x44, 0x2a, 0xe0, 0x32, 0x98, 0x70, 0x22, 0xe5, 0x58,
	0x8a, 0xee, 0x9b, 0xdd, 0xc1, 0x85, 0x55, 0x0f, 0x8a, 0x9a, 0xf0, 0xa4, 0x39, 0x9c, 0xbf, 0xfa,
	0x03, 0xce, 0x46, 0x38, 0xe6, 0x3f, 0x1e, 0x9c, 0x77, 0xe4, 0xc3, 0xc4, 0x31, 0x8e, 0xb9, 0xbd,
	0x7a, 0x5e, 0xec, 0xa5, 0x7e, 0x33, 0x7c, 0xdd, 0xd2, 0x47, 0xe1, 0xf7, 0x57, 0xf4, 0x6d, 0x21,
	0x34, 0x9f, 0xba, 0xdd, 0x55, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x84, 0x75, 0xca, 0xc4, 0xd6,
	0x01, 0x00, 0x00,
}
