// Code generated by yc@v0.0.1. DO NOT EDIT.
import { cos } from './api';

export let prefix = "/api";

export const updateApiPrefix = (apiPrefix: string) => {
  prefix = apiPrefix;
}

export {
  cos
}
