// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package log_server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LogServerClient is the client API for LogServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogServerClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type logServerClient struct {
	cc grpc.ClientConnInterface
}

func NewLogServerClient(cc grpc.ClientConnInterface) LogServerClient {
	return &logServerClient{cc}
}

func (c *logServerClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/log_server.LogServer/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogServerServer is the server API for LogServer service.
// All implementations must embed UnimplementedLogServerServer
// for forward compatibility
type LogServerServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedLogServerServer()
}

// UnimplementedLogServerServer must be embedded to have forward compatible implementations.
type UnimplementedLogServerServer struct {
}

func (UnimplementedLogServerServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedLogServerServer) mustEmbedUnimplementedLogServerServer() {}

// UnsafeLogServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogServerServer will
// result in compilation errors.
type UnsafeLogServerServer interface {
	mustEmbedUnimplementedLogServerServer()
}

func RegisterLogServerServer(s grpc.ServiceRegistrar, srv LogServerServer) {
	s.RegisterService(&LogServer_ServiceDesc, srv)
}

func _LogServer_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServerServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/log_server.LogServer/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServerServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogServer_ServiceDesc is the grpc.ServiceDesc for LogServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "log_server.LogServer",
	HandlerType: (*LogServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _LogServer_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "log_server.proto",
}
