// Code generated by yc. DO NOT EDIT.
package {{.PackageName}}

import (
	"context"
	"fmt"
	"github.com/juxuny/yc"
	"github.com/juxuny/yc/errors"
	"google.golang.org/grpc/metadata"
	"net/http"
)

var globalPrefix = "/api"

func SetPrefix(prefix string) {
	globalPrefix = prefix
}

type Client interface {
{{range $item := .Methods}}{{if ne $item.Desc ""}}	// {{$item.Desc}}
{{end}}	{{$item.MethodName}}(ctx context.Context, req *{{$item.Request}}, extensionMetadata ...metadata.MD) (resp *{{$item.Response}}, err error)
{{end}}
}

type client struct {
	Service      		 string
	signHandler  		 yc.RpcSignContentHandler
	EntrypointDispatcher yc.EntrypointDispatcher
}

var DefaultClient Client

func NewClientWithDispatcher(entrypointDispatcher yc.EntrypointDispatcher) Client {
	return &client{
		Service: Name,
		EntrypointDispatcher: entrypointDispatcher,
	}
}

func Config(entrypointDispatcher yc.EntrypointDispatcher, signHandler yc.RpcSignContentHandler) {
	DefaultClient = &client {
		Service:              Name,
		EntrypointDispatcher: entrypointDispatcher,
		signHandler:          signHandler,
	}
}
{{range $item := .Methods}}
func (t *client) {{$item.MethodName}}(ctx context.Context, req *{{$item.Request}}, extensionMetadata ...metadata.MD) (resp *{{$item.Response}}, err error) {
	md := yc.GetOutgoingHeader(ctx, extensionMetadata...)
	ctx = metadata.NewOutgoingContext(ctx, md)
	resp = &{{$item.Response}}{}
	var code int
	code, err = yc.RpcCall(ctx, t.EntrypointDispatcher.SelectOne(), globalPrefix+"/{{$item.Api}}", req, resp, md, t.signHandler)
	if err != nil {
		return resp, err
	}
	if code != http.StatusOK {
		return resp, errors.SystemError.HttpError.Wrap(fmt.Errorf("http status = %v", code))
	}
	return
}
{{end}}
