// Code generated by yc@{{.CommandLineVersion}}. DO NOT EDIT.
package {{.PackageName}}

import (
    "context"
    "google.golang.org/grpc/metadata"
)

{{range $item := .Methods}}func {{$item.MethodName}}(ctx context.Context, req *{{$item.Request}}, extensionMetadata ...metadata.MD) (resp *{{$item.Response}}, err error) {
    return DefaultClient.{{$item.MethodName}}(ctx, req)
}
{{end}}
