// Code generated by yc@{{.CommandLineVersion}}. DO NOT EDIT.
import { {{.PackageAlias}} } from './api';

export let prefix = "/api";

export const updateApiPrefix = (apiPrefix: string) => {
  prefix = apiPrefix;
}

export {
  {{.PackageAlias}}
}
