// Code generated by yc@{{.CommandLineVersion}}. DO NOT EDIT.
import type * as typing from './typing';
import {doRequest} from '@juxuny/yc-ts-data-type';
import { prefix } from './index'

export class {{.ClassName}} {
{{range $method := .Methods}}{{if ne $method.Desc ""}}  // {{$method.Desc}}{{end}}
  static {{$method.MethodName|lowerFirst}} = (body: typing.{{$method.Request}}, options?: { [key: string]: any }) ={{.Gt}} doRequest{{.Lt}}typing.{{$method.Response}}{{.Gt}}(prefix + '/{{$method.Api}}', { method: 'POST', data: body, ...(options || {}) });
{{end}}
}
