// Code generated by yc@v0.0.1. DO NOT EDIT.
package http

import (
	"context"
	"fmt"
	"github.com/juxuny/yc/log"
	"github.com/juxuny/yc/router"
	cos "github.com/juxuny/yc/services/cos"
	"github.com/juxuny/yc/services/cos/config"
	"github.com/juxuny/yc/services/cos/handler"
	"github.com/juxuny/yc/trace"
)

func Start(ctx context.Context) {
	trace.InitReqId("http")
	router.SetPrefix(config.Env.Prefix)
	if err := router.Register(cos.Name, handler.NewHandler()); err != nil {
		panic(err)
	}
	finished := make(chan bool, 1)
	go func() {
		if err := router.Start(fmt.Sprintf(":%d", config.Env.HttpPort)); err != nil {
			panic(err)
		}
		finished <- true
	}()
	select {
	case <-ctx.Done():
		log.Info("canceled")
		return
	case <-finished:
		log.Info("http server finished")
	}
}
