// Code generated by yc@v0.0.1
package cos

import (
	"github.com/juxuny/yc"
	"github.com/juxuny/yc/env"
)

type _clientEnv struct {
	Entrypoint []string
}

var clientEnv = _clientEnv{}

func init() {
	env.Init(&clientEnv, true, "COS")
	DefaultClient = NewClientWithDispatcher(yc.NewRandomEntrypointDispatcher(clientEnv.Entrypoint))
}
