// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cos.proto

package cos // import "./"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import dt "github.com/juxuny/yc/dt"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ModifyPasswordType int32

const (
	ModifyPasswordType_Unknown ModifyPasswordType = 0
	// 通过旧密码修改
	ModifyPasswordType_OldPassword ModifyPasswordType = 1
	// 通过临时token修改
	ModifyPasswordType_Token ModifyPasswordType = 2
)

var ModifyPasswordType_name = map[int32]string{
	0: "Unknown",
	1: "OldPassword",
	2: "Token",
}
var ModifyPasswordType_value = map[string]int32{
	"Unknown":     0,
	"OldPassword": 1,
	"Token":       2,
}

func (x ModifyPasswordType) String() string {
	return proto.EnumName(ModifyPasswordType_name, int32(x))
}
func (ModifyPasswordType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cos_854b2c7b6f85b4d4, []int{0}
}

type AccountType int32

const (
	AccountType_AccountTypeUnknown  AccountType = 0
	AccountType_AccountTypePassword AccountType = 1
)

var AccountType_name = map[int32]string{
	0: "AccountTypeUnknown",
	1: "AccountTypePassword",
}
var AccountType_value = map[string]int32{
	"AccountTypeUnknown":  0,
	"AccountTypePassword": 1,
}

func (x AccountType) String() string {
	return proto.EnumName(AccountType_name, int32(x))
}
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cos_854b2c7b6f85b4d4, []int{1}
}

type ValueType int32

const (
	ValueType_ValueTypeUnknown ValueType = 0
	ValueType_ValueTypeInt     ValueType = 1
	ValueType_ValueTypeFloat64 ValueType = 2
	ValueType_ValueTypeBool    ValueType = 3
	ValueType_ValueTypeString  ValueType = 4
)

var ValueType_name = map[int32]string{
	0: "ValueTypeUnknown",
	1: "ValueTypeInt",
	2: "ValueTypeFloat64",
	3: "ValueTypeBool",
	4: "ValueTypeString",
}
var ValueType_value = map[string]int32{
	"ValueTypeUnknown": 0,
	"ValueTypeInt":     1,
	"ValueTypeFloat64": 2,
	"ValueTypeBool":    3,
	"ValueTypeString":  4,
}

func (x ValueType) String() string {
	return proto.EnumName(ValueType_name, int32(x))
}
func (ValueType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cos_854b2c7b6f85b4d4, []int{2}
}

type HealthRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *HealthRequest) Reset()         { *m = HealthRequest{} }
func (m *HealthRequest) String() string { return proto.CompactTextString(m) }
func (*HealthRequest) ProtoMessage()    {}
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cos_854b2c7b6f85b4d4, []int{0}
}
func (m *HealthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthRequest.Unmarshal(m, b)
}
func (m *HealthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthRequest.Marshal(b, m, deterministic)
}
func (dst *HealthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthRequest.Merge(dst, src)
}
func (m *HealthRequest) XXX_Size() int {
	return xxx_messageInfo_HealthRequest.Size(m)
}
func (m *HealthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthRequest proto.InternalMessageInfo

type HealthResponse struct {
	CurrentTime          string   `protobuf:"bytes,1,opt,name=currentTime" json:"currentTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *HealthResponse) Reset()         { *m = HealthResponse{} }
func (m *HealthResponse) String() string { return proto.CompactTextString(m) }
func (*HealthResponse) ProtoMessage()    {}
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cos_854b2c7b6f85b4d4, []int{1}
}
func (m *HealthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthResponse.Unmarshal(m, b)
}
func (m *HealthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthResponse.Marshal(b, m, deterministic)
}
func (dst *HealthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthResponse.Merge(dst, src)
}
func (m *HealthResponse) XXX_Size() int {
	return xxx_messageInfo_HealthResponse.Size(m)
}
func (m *HealthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthResponse proto.InternalMessageInfo

func (m *HealthResponse) GetCurrentTime() string {
	if m != nil {
		return m.CurrentTime
	}
	return ""
}

type LoginRequest struct {
	UserName string `protobuf:"bytes,1,opt,name=userName" json:"userName,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	// @v: in: 1
	// @msg: 无效登录类型: {{.AccountType}}
	AccountType          AccountType `protobuf:"varint,3,opt,name=accountType,enum=cos.AccountType" json:"accountType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-" bson:"-"`
	XXX_unrecognized     []byte      `json:"-" bson:"-"`
	XXX_sizecache        int32       `json:"-" bson:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cos_854b2c7b6f85b4d4, []int{2}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (dst *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(dst, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetAccountType() AccountType {
	if m != nil {
		return m.AccountType
	}
	return AccountType_AccountTypeUnknown
}

type LoginResponse struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cos_854b2c7b6f85b4d4, []int{3}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (dst *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(dst, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LoginResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserInfoRequest struct {
	UserId               *dt.ID   `protobuf:"bytes,1,opt,name=userId" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *UserInfoRequest) Reset()         { *m = UserInfoRequest{} }
func (m *UserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UserInfoRequest) ProtoMessage()    {}
func (*UserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cos_854b2c7b6f85b4d4, []int{4}
}
func (m *UserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoRequest.Unmarshal(m, b)
}
func (m *UserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoRequest.Marshal(b, m, deterministic)
}
func (dst *UserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoRequest.Merge(dst, src)
}
func (m *UserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UserInfoRequest.Size(m)
}
func (m *UserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoRequest proto.InternalMessageInfo

func (m *UserInfoRequest) GetUserId() *dt.ID {
	if m != nil {
		return m.UserId
	}
	return nil
}

type UserInfoSimple struct {
	UserId               *dt.ID      `protobuf:"bytes,1,opt,name=userId" json:"userId,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	UserName             string      `protobuf:"bytes,3,opt,name=userName" json:"userName,omitempty"`
	AccountType          AccountType `protobuf:"varint,4,opt,name=accountType,enum=cos.AccountType" json:"accountType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-" bson:"-"`
	XXX_unrecognized     []byte      `json:"-" bson:"-"`
	XXX_sizecache        int32       `json:"-" bson:"-"`
}

func (m *UserInfoSimple) Reset()         { *m = UserInfoSimple{} }
func (m *UserInfoSimple) String() string { return proto.CompactTextString(m) }
func (*UserInfoSimple) ProtoMessage()    {}
func (*UserInfoSimple) Descriptor() ([]byte, []int) {
	return fileDescriptor_cos_854b2c7b6f85b4d4, []int{5}
}
func (m *UserInfoSimple) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoSimple.Unmarshal(m, b)
}
func (m *UserInfoSimple) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoSimple.Marshal(b, m, deterministic)
}
func (dst *UserInfoSimple) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoSimple.Merge(dst, src)
}
func (m *UserInfoSimple) XXX_Size() int {
	return xxx_messageInfo_UserInfoSimple.Size(m)
}
func (m *UserInfoSimple) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoSimple.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoSimple proto.InternalMessageInfo

func (m *UserInfoSimple) GetUserId() *dt.ID {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *UserInfoSimple) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfoSimple) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserInfoSimple) GetAccountType() AccountType {
	if m != nil {
		return m.AccountType
	}
	return AccountType_AccountTypeUnknown
}

// @ref: ModelAccount
type UserInfoResponse struct {
	UserId               *dt.ID      `protobuf:"bytes,1,opt,name=userId" json:"userId,omitempty"`
	Nick                 string      `protobuf:"bytes,2,opt,name=nick" json:"nick,omitempty"`
	Identifier           string      `protobuf:"bytes,3,opt,name=identifier" json:"identifier,omitempty"`
	AccountType          AccountType `protobuf:"varint,4,opt,name=accountType,enum=cos.AccountType" json:"accountType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-" bson:"-"`
	XXX_unrecognized     []byte      `json:"-" bson:"-"`
	XXX_sizecache        int32       `json:"-" bson:"-"`
}

func (m *UserInfoResponse) Reset()         { *m = UserInfoResponse{} }
func (m *UserInfoResponse) String() string { return proto.CompactTextString(m) }
func (*UserInfoResponse) ProtoMessage()    {}
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cos_854b2c7b6f85b4d4, []int{6}
}
func (m *UserInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoResponse.Unmarshal(m, b)
}
func (m *UserInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoResponse.Marshal(b, m, deterministic)
}
func (dst *UserInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoResponse.Merge(dst, src)
}
func (m *UserInfoResponse) XXX_Size() int {
	return xxx_messageInfo_UserInfoResponse.Size(m)
}
func (m *UserInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoResponse proto.InternalMessageInfo

func (m *UserInfoResponse) GetUserId() *dt.ID {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *UserInfoResponse) GetNick() string {
	if m != nil {
		return m.Nick
	}
	return ""
}

func (m *UserInfoResponse) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *UserInfoResponse) GetAccountType() AccountType {
	if m != nil {
		return m.AccountType
	}
	return AccountType_AccountTypeUnknown
}

type UpdateInfoRequest struct {
	UserId *dt.ID `protobuf:"bytes,1,opt,name=userId" json:"userId,omitempty"`
	// @v: length.min=1
	// @msg: missing nick name
	Nick                 string   `protobuf:"bytes,2,opt,name=nick" json:"nick,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *UpdateInfoRequest) Reset()         { *m = UpdateInfoRequest{} }
func (m *UpdateInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateInfoRequest) ProtoMessage()    {}
func (*UpdateInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cos_854b2c7b6f85b4d4, []int{7}
}
func (m *UpdateInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateInfoRequest.Unmarshal(m, b)
}
func (m *UpdateInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateInfoRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateInfoRequest.Merge(dst, src)
}
func (m *UpdateInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateInfoRequest.Size(m)
}
func (m *UpdateInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateInfoRequest proto.InternalMessageInfo

func (m *UpdateInfoRequest) GetUserId() *dt.ID {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *UpdateInfoRequest) GetNick() string {
	if m != nil {
		return m.Nick
	}
	return ""
}

type UpdateInfoResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *UpdateInfoResponse) Reset()         { *m = UpdateInfoResponse{} }
func (m *UpdateInfoResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateInfoResponse) ProtoMessage()    {}
func (*UpdateInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cos_854b2c7b6f85b4d4, []int{8}
}
func (m *UpdateInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateInfoResponse.Unmarshal(m, b)
}
func (m *UpdateInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateInfoResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateInfoResponse.Merge(dst, src)
}
func (m *UpdateInfoResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateInfoResponse.Size(m)
}
func (m *UpdateInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateInfoResponse proto.InternalMessageInfo

type ModifyPasswordRequest struct {
	UserId *dt.ID `protobuf:"bytes,1,opt,name=userId" json:"userId,omitempty"`
	// @v: length.min=6
	// @v: length.max=22
	// @v: password=up|low|num
	// @msg: invalid old password: {{.OldPassword}}
	OldPassword string `protobuf:"bytes,3,opt,name=oldPassword" json:"oldPassword,omitempty"`
	// @v: length.min=6
	// @v: length.max=22
	// @v: password=up|low|num
	// @msg: invalid new password: {{.NewPassword}}
	NewPassword          string   `protobuf:"bytes,4,opt,name=newPassword" json:"newPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ModifyPasswordRequest) Reset()         { *m = ModifyPasswordRequest{} }
func (m *ModifyPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyPasswordRequest) ProtoMessage()    {}
func (*ModifyPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cos_854b2c7b6f85b4d4, []int{9}
}
func (m *ModifyPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyPasswordRequest.Unmarshal(m, b)
}
func (m *ModifyPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyPasswordRequest.Marshal(b, m, deterministic)
}
func (dst *ModifyPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyPasswordRequest.Merge(dst, src)
}
func (m *ModifyPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyPasswordRequest.Size(m)
}
func (m *ModifyPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyPasswordRequest proto.InternalMessageInfo

func (m *ModifyPasswordRequest) GetUserId() *dt.ID {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *ModifyPasswordRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *ModifyPasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ModifyPasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ModifyPasswordResponse) Reset()         { *m = ModifyPasswordResponse{} }
func (m *ModifyPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyPasswordResponse) ProtoMessage()    {}
func (*ModifyPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cos_854b2c7b6f85b4d4, []int{10}
}
func (m *ModifyPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyPasswordResponse.Unmarshal(m, b)
}
func (m *ModifyPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyPasswordResponse.Marshal(b, m, deterministic)
}
func (dst *ModifyPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyPasswordResponse.Merge(dst, src)
}
func (m *ModifyPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ModifyPasswordResponse.Size(m)
}
func (m *ModifyPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyPasswordResponse proto.InternalMessageInfo

type ModelAccount struct {
	// @index
	Id *dt.ID `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// @index
	Identifier string `protobuf:"bytes,2,opt,name=identifier" json:"identifier,omitempty"`
	Credential string `protobuf:"bytes,3,opt,name=credential" json:"credential,omitempty"`
	// @index
	AccountType AccountType `protobuf:"varint,4,opt,name=accountType,enum=cos.AccountType" json:"accountType,omitempty"`
	CreateTime  int64       `protobuf:"varint,5,opt,name=createTime" json:"createTime,omitempty"`
	UpdateTime  int64       `protobuf:"varint,6,opt,name=updateTime" json:"updateTime,omitempty"`
	DeletedAt   int64       `protobuf:"varint,7,opt,name=deletedAt" json:"deletedAt,omitempty"`
	IsDisabled  bool        `protobuf:"varint,8,opt,name=isDisabled" json:"isDisabled,omitempty"`
	// @index
	CreatorId            *dt.ID   `protobuf:"bytes,9,opt,name=creatorId" json:"creatorId,omitempty"`
	Nick                 string   `protobuf:"bytes,10,opt,name=nick" json:"nick,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ModelAccount) Reset()         { *m = ModelAccount{} }
func (m *ModelAccount) String() string { return proto.CompactTextString(m) }
func (*ModelAccount) ProtoMessage()    {}
func (*ModelAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_cos_854b2c7b6f85b4d4, []int{11}
}
func (m *ModelAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelAccount.Unmarshal(m, b)
}
func (m *ModelAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelAccount.Marshal(b, m, deterministic)
}
func (dst *ModelAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelAccount.Merge(dst, src)
}
func (m *ModelAccount) XXX_Size() int {
	return xxx_messageInfo_ModelAccount.Size(m)
}
func (m *ModelAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelAccount.DiscardUnknown(m)
}

var xxx_messageInfo_ModelAccount proto.InternalMessageInfo

func (m *ModelAccount) GetId() *dt.ID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ModelAccount) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *ModelAccount) GetCredential() string {
	if m != nil {
		return m.Credential
	}
	return ""
}

func (m *ModelAccount) GetAccountType() AccountType {
	if m != nil {
		return m.AccountType
	}
	return AccountType_AccountTypeUnknown
}

func (m *ModelAccount) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *ModelAccount) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *ModelAccount) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

func (m *ModelAccount) GetIsDisabled() bool {
	if m != nil {
		return m.IsDisabled
	}
	return false
}

func (m *ModelAccount) GetCreatorId() *dt.ID {
	if m != nil {
		return m.CreatorId
	}
	return nil
}

func (m *ModelAccount) GetNick() string {
	if m != nil {
		return m.Nick
	}
	return ""
}

type ModelNamespace struct {
	// @index
	Id *dt.ID `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// @index
	Namespace  string `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	CreateTime int64  `protobuf:"varint,3,opt,name=createTime" json:"createTime,omitempty"`
	UpdateTime int64  `protobuf:"varint,4,opt,name=updateTime" json:"updateTime,omitempty"`
	DeletedAt  int64  `protobuf:"varint,5,opt,name=deletedAt" json:"deletedAt,omitempty"`
	IsDisabled bool   `protobuf:"varint,6,opt,name=isDisabled" json:"isDisabled,omitempty"`
	// @index
	CreatorId            *dt.ID   `protobuf:"bytes,7,opt,name=creatorId" json:"creatorId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ModelNamespace) Reset()         { *m = ModelNamespace{} }
func (m *ModelNamespace) String() string { return proto.CompactTextString(m) }
func (*ModelNamespace) ProtoMessage()    {}
func (*ModelNamespace) Descriptor() ([]byte, []int) {
	return fileDescriptor_cos_854b2c7b6f85b4d4, []int{12}
}
func (m *ModelNamespace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelNamespace.Unmarshal(m, b)
}
func (m *ModelNamespace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelNamespace.Marshal(b, m, deterministic)
}
func (dst *ModelNamespace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelNamespace.Merge(dst, src)
}
func (m *ModelNamespace) XXX_Size() int {
	return xxx_messageInfo_ModelNamespace.Size(m)
}
func (m *ModelNamespace) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelNamespace.DiscardUnknown(m)
}

var xxx_messageInfo_ModelNamespace proto.InternalMessageInfo

func (m *ModelNamespace) GetId() *dt.ID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ModelNamespace) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ModelNamespace) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *ModelNamespace) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *ModelNamespace) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

func (m *ModelNamespace) GetIsDisabled() bool {
	if m != nil {
		return m.IsDisabled
	}
	return false
}

func (m *ModelNamespace) GetCreatorId() *dt.ID {
	if m != nil {
		return m.CreatorId
	}
	return nil
}

// @ref: ModelNamespace
type NamespaceResp struct {
	Id                   *dt.ID   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	CreateTime           int64    `protobuf:"varint,3,opt,name=createTime" json:"createTime,omitempty"`
	UpdateTime           int64    `protobuf:"varint,4,opt,name=updateTime" json:"updateTime,omitempty"`
	IsDisabled           bool     `protobuf:"varint,6,opt,name=isDisabled" json:"isDisabled,omitempty"`
	CreatorId            *dt.ID   `protobuf:"bytes,7,opt,name=creatorId" json:"creatorId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *NamespaceResp) Reset()         { *m = NamespaceResp{} }
func (m *NamespaceResp) String() string { return proto.CompactTextString(m) }
func (*NamespaceResp) ProtoMessage()    {}
func (*NamespaceResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cos_854b2c7b6f85b4d4, []int{13}
}
func (m *NamespaceResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamespaceResp.Unmarshal(m, b)
}
func (m *NamespaceResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamespaceResp.Marshal(b, m, deterministic)
}
func (dst *NamespaceResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamespaceResp.Merge(dst, src)
}
func (m *NamespaceResp) XXX_Size() int {
	return xxx_messageInfo_NamespaceResp.Size(m)
}
func (m *NamespaceResp) XXX_DiscardUnknown() {
	xxx_messageInfo_NamespaceResp.DiscardUnknown(m)
}

var xxx_messageInfo_NamespaceResp proto.InternalMessageInfo

func (m *NamespaceResp) GetId() *dt.ID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *NamespaceResp) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *NamespaceResp) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *NamespaceResp) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *NamespaceResp) GetIsDisabled() bool {
	if m != nil {
		return m.IsDisabled
	}
	return false
}

func (m *NamespaceResp) GetCreatorId() *dt.ID {
	if m != nil {
		return m.CreatorId
	}
	return nil
}

type ModelConfig struct {
	// @index
	Id         *dt.ID `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	CreateTime int64  `protobuf:"varint,2,opt,name=createTime" json:"createTime,omitempty"`
	UpdateTime int64  `protobuf:"varint,3,opt,name=updateTime" json:"updateTime,omitempty"`
	DeletedAt  int64  `protobuf:"varint,4,opt,name=deletedAt" json:"deletedAt,omitempty"`
	// @index
	ConfigId   string `protobuf:"bytes,5,opt,name=configId" json:"configId,omitempty"`
	IsDisabled bool   `protobuf:"varint,6,opt,name=isDisabled" json:"isDisabled,omitempty"`
	// @index
	CreatorId *dt.ID `protobuf:"bytes,7,opt,name=creatorId" json:"creatorId,omitempty"`
	// @index
	BaseId               *dt.ID   `protobuf:"bytes,8,opt,name=baseId" json:"baseId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ModelConfig) Reset()         { *m = ModelConfig{} }
func (m *ModelConfig) String() string { return proto.CompactTextString(m) }
func (*ModelConfig) ProtoMessage()    {}
func (*ModelConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_cos_854b2c7b6f85b4d4, []int{14}
}
func (m *ModelConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelConfig.Unmarshal(m, b)
}
func (m *ModelConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelConfig.Marshal(b, m, deterministic)
}
func (dst *ModelConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelConfig.Merge(dst, src)
}
func (m *ModelConfig) XXX_Size() int {
	return xxx_messageInfo_ModelConfig.Size(m)
}
func (m *ModelConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ModelConfig proto.InternalMessageInfo

func (m *ModelConfig) GetId() *dt.ID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ModelConfig) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *ModelConfig) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *ModelConfig) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

func (m *ModelConfig) GetConfigId() string {
	if m != nil {
		return m.ConfigId
	}
	return ""
}

func (m *ModelConfig) GetIsDisabled() bool {
	if m != nil {
		return m.IsDisabled
	}
	return false
}

func (m *ModelConfig) GetCreatorId() *dt.ID {
	if m != nil {
		return m.CreatorId
	}
	return nil
}

func (m *ModelConfig) GetBaseId() *dt.ID {
	if m != nil {
		return m.BaseId
	}
	return nil
}

type ConfigResp struct {
	Id                   *dt.ID   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	CreateTime           int64    `protobuf:"varint,2,opt,name=createTime" json:"createTime,omitempty"`
	UpdateTime           int64    `protobuf:"varint,3,opt,name=updateTime" json:"updateTime,omitempty"`
	DeletedAt            int64    `protobuf:"varint,4,opt,name=deletedAt" json:"deletedAt,omitempty"`
	ConfigId             string   `protobuf:"bytes,5,opt,name=configId" json:"configId,omitempty"`
	IsDisabled           bool     `protobuf:"varint,6,opt,name=isDisabled" json:"isDisabled,omitempty"`
	CreatorId            *dt.ID   `protobuf:"bytes,7,opt,name=creatorId" json:"creatorId,omitempty"`
	BaseId               *dt.ID   `protobuf:"bytes,8,opt,name=baseId" json:"baseId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ConfigResp) Reset()         { *m = ConfigResp{} }
func (m *ConfigResp) String() string { return proto.CompactTextString(m) }
func (*ConfigResp) ProtoMessage()    {}
func (*ConfigResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cos_854b2c7b6f85b4d4, []int{15}
}
func (m *ConfigResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigResp.Unmarshal(m, b)
}
func (m *ConfigResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigResp.Marshal(b, m, deterministic)
}
func (dst *ConfigResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigResp.Merge(dst, src)
}
func (m *ConfigResp) XXX_Size() int {
	return xxx_messageInfo_ConfigResp.Size(m)
}
func (m *ConfigResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigResp.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigResp proto.InternalMessageInfo

func (m *ConfigResp) GetId() *dt.ID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ConfigResp) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *ConfigResp) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *ConfigResp) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

func (m *ConfigResp) GetConfigId() string {
	if m != nil {
		return m.ConfigId
	}
	return ""
}

func (m *ConfigResp) GetIsDisabled() bool {
	if m != nil {
		return m.IsDisabled
	}
	return false
}

func (m *ConfigResp) GetCreatorId() *dt.ID {
	if m != nil {
		return m.CreatorId
	}
	return nil
}

func (m *ConfigResp) GetBaseId() *dt.ID {
	if m != nil {
		return m.BaseId
	}
	return nil
}

type ModelKeyValue struct {
	// @index
	Id         *dt.ID `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	CreateTime int64  `protobuf:"varint,2,opt,name=createTime" json:"createTime,omitempty"`
	UpdateTime int64  `protobuf:"varint,3,opt,name=updateTime" json:"updateTime,omitempty"`
	DeletedAt  int64  `protobuf:"varint,4,opt,name=deletedAt" json:"deletedAt,omitempty"`
	IsDisabled bool   `protobuf:"varint,5,opt,name=isDisabled" json:"isDisabled,omitempty"`
	// @index
	ConfigKey   string    `protobuf:"bytes,6,opt,name=configKey" json:"configKey,omitempty"`
	ConfigValue string    `protobuf:"bytes,7,opt,name=configValue" json:"configValue,omitempty"`
	ValueType   ValueType `protobuf:"varint,8,opt,name=valueType,enum=cos.ValueType" json:"valueType,omitempty"`
	// @index
	ConfigId string `protobuf:"bytes,9,opt,name=configId" json:"configId,omitempty"`
	// @index
	CreatorId *dt.ID `protobuf:"bytes,10,opt,name=creatorId" json:"creatorId,omitempty"`
	// @index
	IsHot                bool     `protobuf:"varint,11,opt,name=isHot" json:"isHot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ModelKeyValue) Reset()         { *m = ModelKeyValue{} }
func (m *ModelKeyValue) String() string { return proto.CompactTextString(m) }
func (*ModelKeyValue) ProtoMessage()    {}
func (*ModelKeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_cos_854b2c7b6f85b4d4, []int{16}
}
func (m *ModelKeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelKeyValue.Unmarshal(m, b)
}
func (m *ModelKeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelKeyValue.Marshal(b, m, deterministic)
}
func (dst *ModelKeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelKeyValue.Merge(dst, src)
}
func (m *ModelKeyValue) XXX_Size() int {
	return xxx_messageInfo_ModelKeyValue.Size(m)
}
func (m *ModelKeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelKeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_ModelKeyValue proto.InternalMessageInfo

func (m *ModelKeyValue) GetId() *dt.ID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ModelKeyValue) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *ModelKeyValue) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *ModelKeyValue) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

func (m *ModelKeyValue) GetIsDisabled() bool {
	if m != nil {
		return m.IsDisabled
	}
	return false
}

func (m *ModelKeyValue) GetConfigKey() string {
	if m != nil {
		return m.ConfigKey
	}
	return ""
}

func (m *ModelKeyValue) GetConfigValue() string {
	if m != nil {
		return m.ConfigValue
	}
	return ""
}

func (m *ModelKeyValue) GetValueType() ValueType {
	if m != nil {
		return m.ValueType
	}
	return ValueType_ValueTypeUnknown
}

func (m *ModelKeyValue) GetConfigId() string {
	if m != nil {
		return m.ConfigId
	}
	return ""
}

func (m *ModelKeyValue) GetCreatorId() *dt.ID {
	if m != nil {
		return m.CreatorId
	}
	return nil
}

func (m *ModelKeyValue) GetIsHot() bool {
	if m != nil {
		return m.IsHot
	}
	return false
}

// @ref: ModelKeyValue
type KeyValueResp struct {
	Id                   *dt.ID    `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	CreateTime           int64     `protobuf:"varint,2,opt,name=createTime" json:"createTime,omitempty"`
	UpdateTime           int64     `protobuf:"varint,3,opt,name=updateTime" json:"updateTime,omitempty"`
	DeletedAt            int64     `protobuf:"varint,4,opt,name=deletedAt" json:"deletedAt,omitempty"`
	IsDisabled           bool      `protobuf:"varint,5,opt,name=isDisabled" json:"isDisabled,omitempty"`
	ConfigKey            string    `protobuf:"bytes,6,opt,name=configKey" json:"configKey,omitempty"`
	ConfigValue          string    `protobuf:"bytes,7,opt,name=configValue" json:"configValue,omitempty"`
	ValueType            ValueType `protobuf:"varint,8,opt,name=valueType,enum=cos.ValueType" json:"valueType,omitempty"`
	ConfigId             string    `protobuf:"bytes,9,opt,name=configId" json:"configId,omitempty"`
	CreatorId            *dt.ID    `protobuf:"bytes,10,opt,name=creatorId" json:"creatorId,omitempty"`
	IsHot                bool      `protobuf:"varint,11,opt,name=isHot" json:"isHot,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-" bson:"-"`
	XXX_unrecognized     []byte    `json:"-" bson:"-"`
	XXX_sizecache        int32     `json:"-" bson:"-"`
}

func (m *KeyValueResp) Reset()         { *m = KeyValueResp{} }
func (m *KeyValueResp) String() string { return proto.CompactTextString(m) }
func (*KeyValueResp) ProtoMessage()    {}
func (*KeyValueResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cos_854b2c7b6f85b4d4, []int{17}
}
func (m *KeyValueResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValueResp.Unmarshal(m, b)
}
func (m *KeyValueResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValueResp.Marshal(b, m, deterministic)
}
func (dst *KeyValueResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValueResp.Merge(dst, src)
}
func (m *KeyValueResp) XXX_Size() int {
	return xxx_messageInfo_KeyValueResp.Size(m)
}
func (m *KeyValueResp) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValueResp.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValueResp proto.InternalMessageInfo

func (m *KeyValueResp) GetId() *dt.ID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *KeyValueResp) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *KeyValueResp) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *KeyValueResp) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

func (m *KeyValueResp) GetIsDisabled() bool {
	if m != nil {
		return m.IsDisabled
	}
	return false
}

func (m *KeyValueResp) GetConfigKey() string {
	if m != nil {
		return m.ConfigKey
	}
	return ""
}

func (m *KeyValueResp) GetConfigValue() string {
	if m != nil {
		return m.ConfigValue
	}
	return ""
}

func (m *KeyValueResp) GetValueType() ValueType {
	if m != nil {
		return m.ValueType
	}
	return ValueType_ValueTypeUnknown
}

func (m *KeyValueResp) GetConfigId() string {
	if m != nil {
		return m.ConfigId
	}
	return ""
}

func (m *KeyValueResp) GetCreatorId() *dt.ID {
	if m != nil {
		return m.CreatorId
	}
	return nil
}

func (m *KeyValueResp) GetIsHot() bool {
	if m != nil {
		return m.IsHot
	}
	return false
}

type SaveOrCreateUserRequest struct {
	Identifier string `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	Credential string `protobuf:"bytes,2,opt,name=credential" json:"credential,omitempty"`
	// @v: in=1
	// @msg: invalid accountType: {{.AccountType|num}}
	AccountType          AccountType `protobuf:"varint,3,opt,name=AccountType,enum=cos.AccountType" json:"AccountType,omitempty"`
	UserId               *dt.ID      `protobuf:"bytes,4,opt,name=userId" json:"userId,omitempty"`
	Nick                 string      `protobuf:"bytes,5,opt,name=nick" json:"nick,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-" bson:"-"`
	XXX_unrecognized     []byte      `json:"-" bson:"-"`
	XXX_sizecache        int32       `json:"-" bson:"-"`
}

func (m *SaveOrCreateUserRequest) Reset()         { *m = SaveOrCreateUserRequest{} }
func (m *SaveOrCreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*SaveOrCreateUserRequest) ProtoMessage()    {}
func (*SaveOrCreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cos_854b2c7b6f85b4d4, []int{18}
}
func (m *SaveOrCreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveOrCreateUserRequest.Unmarshal(m, b)
}
func (m *SaveOrCreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveOrCreateUserRequest.Marshal(b, m, deterministic)
}
func (dst *SaveOrCreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveOrCreateUserRequest.Merge(dst, src)
}
func (m *SaveOrCreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_SaveOrCreateUserRequest.Size(m)
}
func (m *SaveOrCreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveOrCreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveOrCreateUserRequest proto.InternalMessageInfo

func (m *SaveOrCreateUserRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *SaveOrCreateUserRequest) GetCredential() string {
	if m != nil {
		return m.Credential
	}
	return ""
}

func (m *SaveOrCreateUserRequest) GetAccountType() AccountType {
	if m != nil {
		return m.AccountType
	}
	return AccountType_AccountTypeUnknown
}

func (m *SaveOrCreateUserRequest) GetUserId() *dt.ID {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *SaveOrCreateUserRequest) GetNick() string {
	if m != nil {
		return m.Nick
	}
	return ""
}

type SaveOrCreateUserResponse struct {
	UserId               *dt.ID   `protobuf:"bytes,1,opt,name=userId" json:"userId,omitempty"`
	IsNew                bool     `protobuf:"varint,2,opt,name=isNew" json:"isNew,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *SaveOrCreateUserResponse) Reset()         { *m = SaveOrCreateUserResponse{} }
func (m *SaveOrCreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*SaveOrCreateUserResponse) ProtoMessage()    {}
func (*SaveOrCreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cos_854b2c7b6f85b4d4, []int{19}
}
func (m *SaveOrCreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveOrCreateUserResponse.Unmarshal(m, b)
}
func (m *SaveOrCreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveOrCreateUserResponse.Marshal(b, m, deterministic)
}
func (dst *SaveOrCreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveOrCreateUserResponse.Merge(dst, src)
}
func (m *SaveOrCreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_SaveOrCreateUserResponse.Size(m)
}
func (m *SaveOrCreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveOrCreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveOrCreateUserResponse proto.InternalMessageInfo

func (m *SaveOrCreateUserResponse) GetUserId() *dt.ID {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *SaveOrCreateUserResponse) GetIsNew() bool {
	if m != nil {
		return m.IsNew
	}
	return false
}

type SaveNamespaceRequest struct {
	// @v: length.min=3
	// @msg: invalid namespace: {{.Namespace}}
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
	Id                   *dt.ID   `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *SaveNamespaceRequest) Reset()         { *m = SaveNamespaceRequest{} }
func (m *SaveNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*SaveNamespaceRequest) ProtoMessage()    {}
func (*SaveNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cos_854b2c7b6f85b4d4, []int{20}
}
func (m *SaveNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveNamespaceRequest.Unmarshal(m, b)
}
func (m *SaveNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveNamespaceRequest.Marshal(b, m, deterministic)
}
func (dst *SaveNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveNamespaceRequest.Merge(dst, src)
}
func (m *SaveNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_SaveNamespaceRequest.Size(m)
}
func (m *SaveNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveNamespaceRequest proto.InternalMessageInfo

func (m *SaveNamespaceRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *SaveNamespaceRequest) GetId() *dt.ID {
	if m != nil {
		return m.Id
	}
	return nil
}

type SaveNamespaceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *SaveNamespaceResponse) Reset()         { *m = SaveNamespaceResponse{} }
func (m *SaveNamespaceResponse) String() string { return proto.CompactTextString(m) }
func (*SaveNamespaceResponse) ProtoMessage()    {}
func (*SaveNamespaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cos_854b2c7b6f85b4d4, []int{21}
}
func (m *SaveNamespaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveNamespaceResponse.Unmarshal(m, b)
}
func (m *SaveNamespaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveNamespaceResponse.Marshal(b, m, deterministic)
}
func (dst *SaveNamespaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveNamespaceResponse.Merge(dst, src)
}
func (m *SaveNamespaceResponse) XXX_Size() int {
	return xxx_messageInfo_SaveNamespaceResponse.Size(m)
}
func (m *SaveNamespaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveNamespaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveNamespaceResponse proto.InternalMessageInfo

type ListNamespaceRequest struct {
	Pagination           *dt.Pagination `protobuf:"bytes,1,opt,name=pagination" json:"pagination,omitempty"`
	SearchKey            string         `protobuf:"bytes,2,opt,name=searchKey" json:"searchKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-" bson:"-"`
	XXX_unrecognized     []byte         `json:"-" bson:"-"`
	XXX_sizecache        int32          `json:"-" bson:"-"`
}

func (m *ListNamespaceRequest) Reset()         { *m = ListNamespaceRequest{} }
func (m *ListNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*ListNamespaceRequest) ProtoMessage()    {}
func (*ListNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cos_854b2c7b6f85b4d4, []int{22}
}
func (m *ListNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNamespaceRequest.Unmarshal(m, b)
}
func (m *ListNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNamespaceRequest.Marshal(b, m, deterministic)
}
func (dst *ListNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNamespaceRequest.Merge(dst, src)
}
func (m *ListNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_ListNamespaceRequest.Size(m)
}
func (m *ListNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListNamespaceRequest proto.InternalMessageInfo

func (m *ListNamespaceRequest) GetPagination() *dt.Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *ListNamespaceRequest) GetSearchKey() string {
	if m != nil {
		return m.SearchKey
	}
	return ""
}

// @ref: ModelNamespace
type ListNamespaceItem struct {
	Id                   *dt.ID   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ListNamespaceItem) Reset()         { *m = ListNamespaceItem{} }
func (m *ListNamespaceItem) String() string { return proto.CompactTextString(m) }
func (*ListNamespaceItem) ProtoMessage()    {}
func (*ListNamespaceItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_cos_854b2c7b6f85b4d4, []int{23}
}
func (m *ListNamespaceItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNamespaceItem.Unmarshal(m, b)
}
func (m *ListNamespaceItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNamespaceItem.Marshal(b, m, deterministic)
}
func (dst *ListNamespaceItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNamespaceItem.Merge(dst, src)
}
func (m *ListNamespaceItem) XXX_Size() int {
	return xxx_messageInfo_ListNamespaceItem.Size(m)
}
func (m *ListNamespaceItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNamespaceItem.DiscardUnknown(m)
}

var xxx_messageInfo_ListNamespaceItem proto.InternalMessageInfo

func (m *ListNamespaceItem) GetId() *dt.ID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ListNamespaceItem) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type ListNamespaceResponse struct {
	Pagination           *dt.PaginationResp   `protobuf:"bytes,1,opt,name=pagination" json:"pagination,omitempty"`
	List                 []*ListNamespaceItem `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *ListNamespaceResponse) Reset()         { *m = ListNamespaceResponse{} }
func (m *ListNamespaceResponse) String() string { return proto.CompactTextString(m) }
func (*ListNamespaceResponse) ProtoMessage()    {}
func (*ListNamespaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cos_854b2c7b6f85b4d4, []int{24}
}
func (m *ListNamespaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNamespaceResponse.Unmarshal(m, b)
}
func (m *ListNamespaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNamespaceResponse.Marshal(b, m, deterministic)
}
func (dst *ListNamespaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNamespaceResponse.Merge(dst, src)
}
func (m *ListNamespaceResponse) XXX_Size() int {
	return xxx_messageInfo_ListNamespaceResponse.Size(m)
}
func (m *ListNamespaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNamespaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListNamespaceResponse proto.InternalMessageInfo

func (m *ListNamespaceResponse) GetPagination() *dt.PaginationResp {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *ListNamespaceResponse) GetList() []*ListNamespaceItem {
	if m != nil {
		return m.List
	}
	return nil
}

type DeleteNamespaceRequest struct {
	Id                   *dt.ID   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *DeleteNamespaceRequest) Reset()         { *m = DeleteNamespaceRequest{} }
func (m *DeleteNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteNamespaceRequest) ProtoMessage()    {}
func (*DeleteNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cos_854b2c7b6f85b4d4, []int{25}
}
func (m *DeleteNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNamespaceRequest.Unmarshal(m, b)
}
func (m *DeleteNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNamespaceRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNamespaceRequest.Merge(dst, src)
}
func (m *DeleteNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteNamespaceRequest.Size(m)
}
func (m *DeleteNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNamespaceRequest proto.InternalMessageInfo

func (m *DeleteNamespaceRequest) GetId() *dt.ID {
	if m != nil {
		return m.Id
	}
	return nil
}

type DeleteNamespaceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *DeleteNamespaceResponse) Reset()         { *m = DeleteNamespaceResponse{} }
func (m *DeleteNamespaceResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteNamespaceResponse) ProtoMessage()    {}
func (*DeleteNamespaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cos_854b2c7b6f85b4d4, []int{26}
}
func (m *DeleteNamespaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNamespaceResponse.Unmarshal(m, b)
}
func (m *DeleteNamespaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNamespaceResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteNamespaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNamespaceResponse.Merge(dst, src)
}
func (m *DeleteNamespaceResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteNamespaceResponse.Size(m)
}
func (m *DeleteNamespaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNamespaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNamespaceResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*HealthRequest)(nil), "cos.HealthRequest")
	proto.RegisterType((*HealthResponse)(nil), "cos.HealthResponse")
	proto.RegisterType((*LoginRequest)(nil), "cos.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "cos.LoginResponse")
	proto.RegisterType((*UserInfoRequest)(nil), "cos.UserInfoRequest")
	proto.RegisterType((*UserInfoSimple)(nil), "cos.UserInfoSimple")
	proto.RegisterType((*UserInfoResponse)(nil), "cos.UserInfoResponse")
	proto.RegisterType((*UpdateInfoRequest)(nil), "cos.UpdateInfoRequest")
	proto.RegisterType((*UpdateInfoResponse)(nil), "cos.UpdateInfoResponse")
	proto.RegisterType((*ModifyPasswordRequest)(nil), "cos.ModifyPasswordRequest")
	proto.RegisterType((*ModifyPasswordResponse)(nil), "cos.ModifyPasswordResponse")
	proto.RegisterType((*ModelAccount)(nil), "cos.ModelAccount")
	proto.RegisterType((*ModelNamespace)(nil), "cos.ModelNamespace")
	proto.RegisterType((*NamespaceResp)(nil), "cos.NamespaceResp")
	proto.RegisterType((*ModelConfig)(nil), "cos.ModelConfig")
	proto.RegisterType((*ConfigResp)(nil), "cos.ConfigResp")
	proto.RegisterType((*ModelKeyValue)(nil), "cos.ModelKeyValue")
	proto.RegisterType((*KeyValueResp)(nil), "cos.KeyValueResp")
	proto.RegisterType((*SaveOrCreateUserRequest)(nil), "cos.SaveOrCreateUserRequest")
	proto.RegisterType((*SaveOrCreateUserResponse)(nil), "cos.SaveOrCreateUserResponse")
	proto.RegisterType((*SaveNamespaceRequest)(nil), "cos.SaveNamespaceRequest")
	proto.RegisterType((*SaveNamespaceResponse)(nil), "cos.SaveNamespaceResponse")
	proto.RegisterType((*ListNamespaceRequest)(nil), "cos.ListNamespaceRequest")
	proto.RegisterType((*ListNamespaceItem)(nil), "cos.ListNamespaceItem")
	proto.RegisterType((*ListNamespaceResponse)(nil), "cos.ListNamespaceResponse")
	proto.RegisterType((*DeleteNamespaceRequest)(nil), "cos.DeleteNamespaceRequest")
	proto.RegisterType((*DeleteNamespaceResponse)(nil), "cos.DeleteNamespaceResponse")
	proto.RegisterEnum("cos.ModifyPasswordType", ModifyPasswordType_name, ModifyPasswordType_value)
	proto.RegisterEnum("cos.AccountType", AccountType_name, AccountType_value)
	proto.RegisterEnum("cos.ValueType", ValueType_name, ValueType_value)
}

func init() { proto.RegisterFile("cos.proto", fileDescriptor_cos_854b2c7b6f85b4d4) }

var fileDescriptor_cos_854b2c7b6f85b4d4 = []byte{
	// 1225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x58, 0x5f, 0x6f, 0xe3, 0x44,
	0x10, 0x3f, 0x3b, 0x4e, 0x1a, 0x4f, 0x9a, 0xd4, 0xdd, 0xa6, 0x69, 0xce, 0x94, 0x2a, 0xb2, 0x78,
	0xa8, 0x2a, 0x94, 0x3b, 0x72, 0x08, 0x09, 0x21, 0x40, 0xbd, 0x56, 0xd0, 0x5c, 0x7b, 0xbd, 0x9e,
	0xdb, 0xde, 0x03, 0x2f, 0x95, 0x6b, 0x6f, 0x7b, 0xa6, 0xae, 0x37, 0x17, 0x6f, 0x2e, 0x84, 0x37,
	0x24, 0xf8, 0x06, 0x3c, 0xf1, 0x6d, 0xf8, 0x08, 0xf0, 0x31, 0x0e, 0x3e, 0x04, 0xda, 0xf5, 0xbf,
	0xb5, 0xe3, 0xa4, 0xa5, 0x3a, 0xa9, 0x12, 0xbc, 0x79, 0x7f, 0x3b, 0x3b, 0x3b, 0xf3, 0x9b, 0xd9,
	0x9d, 0x59, 0x83, 0x6a, 0x93, 0xa0, 0x3b, 0x18, 0x12, 0x4a, 0x50, 0xc9, 0x26, 0x81, 0xae, 0x3b,
	0xf4, 0xd1, 0xf7, 0xa3, 0x1f, 0x46, 0xfe, 0xe4, 0x6c, 0x62, 0x9f, 0x39, 0xf4, 0xec, 0xdc, 0x0a,
	0x70, 0x28, 0x60, 0x2c, 0x41, 0x7d, 0x0f, 0x5b, 0x1e, 0x7d, 0x6d, 0xe2, 0x37, 0x23, 0x1c, 0x50,
	0xa3, 0x07, 0x8d, 0x18, 0x08, 0x06, 0xc4, 0x0f, 0x30, 0xea, 0x40, 0xcd, 0x1e, 0x0d, 0x87, 0xd8,
	0xa7, 0x27, 0xee, 0x35, 0x6e, 0x4b, 0x1d, 0x69, 0x53, 0x35, 0x45, 0xc8, 0xf8, 0x11, 0x16, 0x0f,
	0xc8, 0xa5, 0xeb, 0x47, 0x3a, 0x90, 0x0e, 0xd5, 0x51, 0x80, 0x87, 0x87, 0x56, 0x22, 0x9e, 0x8c,
	0xd9, 0xdc, 0xc0, 0x0a, 0x82, 0x31, 0x19, 0x3a, 0x6d, 0x39, 0x9c, 0x8b, 0xc7, 0xa8, 0x07, 0x35,
	0xcb, 0xb6, 0xc9, 0xc8, 0xa7, 0x27, 0x93, 0x01, 0x6e, 0x97, 0x3a, 0xd2, 0x66, 0xa3, 0xa7, 0x75,
	0x99, 0x3b, 0xdb, 0x29, 0x6e, 0x8a, 0x42, 0xc6, 0x4b, 0xa8, 0x47, 0x7b, 0x47, 0xe6, 0xb6, 0xa0,
	0xc2, 0x36, 0xeb, 0x3b, 0x7c, 0x6b, 0xc5, 0x8c, 0x46, 0x08, 0x81, 0xe2, 0x33, 0x83, 0xc2, 0x4d,
	0xf9, 0x37, 0x6a, 0x42, 0x99, 0x92, 0x2b, 0xec, 0xf3, 0xad, 0x54, 0x33, 0x1c, 0x18, 0x9f, 0xc0,
	0xd2, 0x29, 0x5b, 0xe3, 0x5f, 0x90, 0xd8, 0xa3, 0x8d, 0x8c, 0xd2, 0x5a, 0xaf, 0xd2, 0x75, 0x68,
	0xb7, 0xbf, 0x1b, 0x2b, 0x37, 0x7e, 0x95, 0xa0, 0x11, 0xaf, 0x39, 0x76, 0xaf, 0x07, 0x1e, 0xbe,
	0x69, 0x49, 0xa1, 0x3d, 0x22, 0x71, 0xa5, 0x1c, 0x71, 0x39, 0x72, 0x94, 0xdb, 0x90, 0xf3, 0x9b,
	0x04, 0x5a, 0xea, 0x4a, 0x44, 0xd0, 0x6d, 0x0c, 0x73, 0xed, 0xab, 0xc4, 0x30, 0xd7, 0xbe, 0x42,
	0x1b, 0x00, 0xae, 0x83, 0x7d, 0xea, 0x5e, 0xb8, 0x78, 0x18, 0x99, 0x26, 0x20, 0x77, 0x32, 0xee,
	0x5b, 0x58, 0x3e, 0x1d, 0x38, 0x16, 0xc5, 0xff, 0x82, 0xe8, 0x22, 0xe3, 0x8c, 0x26, 0x20, 0x51,
	0x51, 0xe8, 0xa6, 0xf1, 0x93, 0x04, 0xab, 0xcf, 0x89, 0xe3, 0x5e, 0x4c, 0x8e, 0xa2, 0xfc, 0xba,
	0xed, 0x1e, 0x1d, 0xa8, 0x11, 0xcf, 0x89, 0x57, 0x45, 0xde, 0x8a, 0x10, 0x93, 0xf0, 0xf1, 0x38,
	0x91, 0x50, 0x42, 0x09, 0x01, 0x7a, 0xa6, 0x54, 0x65, 0xad, 0x64, 0xb4, 0xa1, 0x95, 0x37, 0x21,
	0xb2, 0xee, 0x4f, 0x19, 0x16, 0x9f, 0x13, 0x07, 0x7b, 0x11, 0x3d, 0xa8, 0x05, 0xb2, 0x9b, 0x37,
	0x48, 0x76, 0x9d, 0x1c, 0xf3, 0xf2, 0x14, 0xf3, 0x1b, 0x00, 0xf6, 0x10, 0xf3, 0xb1, 0xe5, 0xc5,
	0x91, 0x49, 0x91, 0xbb, 0x44, 0x26, 0xd2, 0x69, 0x51, 0xcc, 0x0f, 0x7c, 0xb9, 0x23, 0x6d, 0x96,
	0x4c, 0x01, 0x61, 0xf3, 0x23, 0x4e, 0x38, 0x9f, 0xaf, 0x84, 0xf3, 0x29, 0x82, 0xd6, 0x41, 0x75,
	0xb0, 0x87, 0x29, 0x76, 0xb6, 0x69, 0x7b, 0x81, 0x4f, 0xa7, 0x00, 0xf7, 0x28, 0xd8, 0x75, 0x03,
	0xeb, 0xdc, 0xc3, 0x4e, 0xbb, 0xda, 0x91, 0x36, 0xab, 0xa6, 0x80, 0xa0, 0x8f, 0x40, 0xe5, 0x7b,
	0x11, 0x16, 0x21, 0x35, 0x43, 0x48, 0x3a, 0x91, 0x24, 0x02, 0x08, 0x89, 0xf0, 0x4e, 0x82, 0x06,
	0x27, 0x95, 0x1d, 0x98, 0x60, 0x60, 0xd9, 0x78, 0x26, 0xad, 0xeb, 0xa0, 0xfa, 0xb1, 0x50, 0xc4,
	0x6a, 0x0a, 0xe4, 0x08, 0x28, 0xdd, 0x40, 0x80, 0x32, 0x9f, 0x80, 0xf2, 0x7c, 0x02, 0x2a, 0xf3,
	0x09, 0x58, 0x98, 0x41, 0x80, 0xf1, 0x87, 0x04, 0xf5, 0xc4, 0x4f, 0x96, 0x57, 0xf7, 0xe4, 0xeb,
	0x7b, 0xf1, 0xe6, 0x99, 0x52, 0x2d, 0x6b, 0x15, 0xe3, 0x17, 0x19, 0x6a, 0x3c, 0x80, 0x3b, 0xc4,
	0xbf, 0x70, 0x2f, 0xe7, 0x1d, 0x0a, 0xc1, 0x66, 0xf9, 0x06, 0x9b, 0x4b, 0xf3, 0xe3, 0xa3, 0xe4,
	0xe3, 0xa3, 0x43, 0xd5, 0xe6, 0xfb, 0xf7, 0x1d, 0x1e, 0x3c, 0xd5, 0x4c, 0xc6, 0xef, 0xc7, 0x5b,
	0x76, 0x03, 0xb1, 0x1a, 0xdc, 0x0f, 0xd3, 0x5f, 0xb8, 0x81, 0x42, 0xd4, 0xf8, 0x59, 0x06, 0x08,
	0x29, 0x98, 0x1b, 0xd8, 0xff, 0x3a, 0x0d, 0x7f, 0xc9, 0x50, 0xe7, 0xe9, 0xb0, 0x8f, 0x27, 0xaf,
	0x2c, 0x6f, 0x84, 0xef, 0x89, 0x89, 0xac, 0xb7, 0xe5, 0x29, 0x6f, 0xd7, 0x59, 0xcb, 0xc5, 0x98,
	0xd9, 0xc7, 0x13, 0x4e, 0x86, 0x6a, 0xa6, 0x00, 0xef, 0x9f, 0xf8, 0x80, 0xbb, 0xc0, 0xd9, 0x60,
	0xfd, 0x53, 0x0a, 0xa1, 0x8f, 0x41, 0x7d, 0xcb, 0x3e, 0xf8, 0x0d, 0x5d, 0xe5, 0x37, 0x74, 0x83,
	0xdf, 0xd0, 0xaf, 0x62, 0xd4, 0x4c, 0x05, 0x32, 0x71, 0x51, 0x73, 0x71, 0xc9, 0xf0, 0x0e, 0xb3,
	0x78, 0x6f, 0x42, 0xd9, 0x0d, 0xf6, 0x08, 0x6d, 0xd7, 0xb8, 0x2b, 0xe1, 0xc0, 0x78, 0x27, 0xc3,
	0x62, 0x4c, 0xf4, 0x3d, 0xa6, 0xdd, 0xff, 0x83, 0xec, 0xdf, 0x25, 0x58, 0x3b, 0xb6, 0xde, 0xe2,
	0x17, 0xc3, 0x1d, 0x4e, 0x1c, 0xeb, 0xd2, 0xd2, 0xfe, 0x44, 0x2c, 0xf9, 0xd2, 0x0d, 0x25, 0x5f,
	0x2e, 0x2a, 0xf9, 0xdb, 0xb7, 0x69, 0xa3, 0xb7, 0x33, 0x25, 0x3f, 0xee, 0x89, 0x94, 0xb9, 0x7d,
	0x57, 0x59, 0x28, 0xb7, 0x47, 0xd0, 0x9e, 0x76, 0xe1, 0x96, 0x4d, 0x26, 0x67, 0xe5, 0x10, 0x8f,
	0xb9, 0xf9, 0x9c, 0x95, 0x43, 0x3c, 0x36, 0x0e, 0xa0, 0xc9, 0x34, 0x0a, 0x65, 0x2d, 0x64, 0x24,
	0x53, 0xc1, 0xa4, 0x7c, 0x05, 0x0b, 0xf3, 0x54, 0xce, 0xe7, 0xa9, 0xb1, 0x06, 0xab, 0x39, 0x6d,
	0x51, 0xf3, 0xe5, 0x40, 0xf3, 0xc0, 0x0d, 0xe8, 0xd4, 0x36, 0x5d, 0x80, 0x81, 0x75, 0xe9, 0xfa,
	0x16, 0x75, 0x89, 0x1f, 0x19, 0xde, 0x60, 0x0a, 0x8f, 0x12, 0xd4, 0x14, 0x24, 0x98, 0x59, 0x01,
	0xb6, 0x86, 0xf6, 0x6b, 0x96, 0x8a, 0x51, 0x61, 0x4d, 0x00, 0xa3, 0x0f, 0xcb, 0x99, 0x5d, 0xfa,
	0x14, 0x5f, 0xdf, 0xad, 0x46, 0x1b, 0x63, 0x58, 0xcd, 0x19, 0x1c, 0xd1, 0xdc, 0x2b, 0xb0, 0x18,
	0xe5, 0x2c, 0xc6, 0xc1, 0x20, 0x63, 0xf5, 0x16, 0x28, 0x9e, 0x1b, 0xd0, 0xb6, 0xdc, 0x29, 0x6d,
	0xd6, 0x7a, 0x2d, 0x9e, 0x17, 0x53, 0x86, 0x9a, 0x5c, 0xc6, 0x78, 0x0c, 0xad, 0x5d, 0x7e, 0x32,
	0xa7, 0xb8, 0x9a, 0xe1, 0x88, 0xf1, 0x10, 0xd6, 0xa6, 0x56, 0x84, 0xc6, 0x6e, 0x7d, 0x09, 0x28,
	0xdb, 0x0d, 0xf3, 0xcc, 0xab, 0xc1, 0xc2, 0xa9, 0x7f, 0xe5, 0x93, 0xb1, 0xaf, 0x3d, 0x40, 0x4b,
	0x50, 0x7b, 0x91, 0xf6, 0xd9, 0x9a, 0x84, 0x54, 0x28, 0x9f, 0xb0, 0x47, 0x99, 0x26, 0x6f, 0x7d,
	0x95, 0x49, 0x6b, 0xd4, 0x02, 0x24, 0x0c, 0x53, 0x15, 0x6b, 0xb0, 0x22, 0xe0, 0xa9, 0xaa, 0xad,
	0x37, 0xa0, 0x26, 0x47, 0x1c, 0x35, 0x41, 0x4b, 0x06, 0xe9, 0x5a, 0x0d, 0x16, 0x13, 0xb4, 0xef,
	0x53, 0x4d, 0xca, 0xc8, 0x7d, 0xe3, 0x11, 0x8b, 0x7e, 0xf6, 0xa9, 0x26, 0xa3, 0x65, 0xa8, 0x27,
	0xe8, 0x53, 0x42, 0x3c, 0xad, 0x84, 0x56, 0x60, 0x29, 0x81, 0x8e, 0xe9, 0xd0, 0xf5, 0x2f, 0x35,
	0xa5, 0xf7, 0xb7, 0x02, 0xa5, 0x1d, 0x12, 0xa0, 0x27, 0x50, 0x09, 0x1f, 0xd5, 0x08, 0x71, 0xba,
	0x33, 0x4f, 0x6e, 0x7d, 0x25, 0x83, 0x45, 0x39, 0xfa, 0x00, 0x3d, 0x86, 0x32, 0x7f, 0xd9, 0xa2,
	0xe5, 0x30, 0x44, 0xc2, 0x0b, 0x5b, 0x47, 0x22, 0x94, 0xac, 0xf8, 0x1c, 0xaa, 0xf1, 0x6b, 0x0f,
	0x35, 0xb9, 0x44, 0xee, 0x1d, 0xab, 0xaf, 0xe6, 0xd0, 0x64, 0xe9, 0xd7, 0x00, 0xe9, 0x1b, 0x0a,
	0x85, 0x49, 0x31, 0xf5, 0x3a, 0xd3, 0xd7, 0xa6, 0xf0, 0x44, 0xc1, 0x3e, 0x6f, 0xbd, 0x85, 0xe0,
	0x22, 0x9d, 0x0b, 0x17, 0x3e, 0xc1, 0xf4, 0x0f, 0x0a, 0xe7, 0x12, 0x65, 0x2f, 0x41, 0xcb, 0xdf,
	0x2c, 0x68, 0x9d, 0x2f, 0x99, 0x71, 0x67, 0xea, 0x1f, 0xce, 0x98, 0x4d, 0x54, 0xee, 0x41, 0x3d,
	0x73, 0x19, 0xa0, 0x87, 0xc9, 0x8a, 0x7c, 0x6e, 0xeb, 0x7a, 0xd1, 0x94, 0xa8, 0x29, 0x73, 0x5c,
	0x22, 0x4d, 0x45, 0x37, 0x4a, 0xa4, 0xa9, 0xf0, 0xec, 0x1a, 0x0f, 0xd0, 0x21, 0x2c, 0xe5, 0xce,
	0x0a, 0x0a, 0x89, 0x29, 0x3e, 0x73, 0xfa, 0x7a, 0xf1, 0x64, 0xac, 0xef, 0x69, 0xf5, 0xbb, 0x4a,
	0xf7, 0xd1, 0x17, 0x36, 0x09, 0xce, 0x2b, 0xfc, 0xef, 0xce, 0x93, 0x7f, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x61, 0xed, 0x2a, 0xdd, 0x0b, 0x12, 0x00, 0x00,
}
