// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
package cos

import (
	"github.com/juxuny/yc/validator"
)

const (
	ValidatorTemplateModifyPasswordRequestToken = "无效凭证"
)

var templateList = []string{
	ValidatorTemplateModifyPasswordRequestToken,
}

func init() {
	if err := validator.RegisterTemplate(templateList...); err != nil {
		panic(err)
	}
}

func (m *HealthRequest) Validate() error {
	return nil
}
func (m *LoginRequest) Validate() error {
	return nil
}
func (m *UserInfoRequest) Validate() error {
	return nil
}
func (m *UpdateInfoRequest) Validate() error {
	return nil
}
func (m *ModifyPasswordRequest) Validate() error {
	if err := validator.Run(m.Token, validator.CreateAction("length.min", "5", ValidatorTemplateModifyPasswordRequestToken), m, "token"); err != nil {
		return err
	}
	if err := validator.Run(m.Token, validator.CreateAction("length.max", "32", ValidatorTemplateModifyPasswordRequestToken), m, "token"); err != nil {
		return err
	}
	return nil
}
func (m *CreateUserRequest) Validate() error {
	return nil
}
func (m *SaveNamespaceRequest) Validate() error {
	return nil
}
func (m *ListNamespaceRequest) Validate() error {
	return nil
}
func (m *DeleteNamespaceRequest) Validate() error {
	return nil
}
