// Code generated by yc. DO NOT EDIT.
package cos

import "google.golang.org/protobuf/proto"

func (m *HealthRequest) Clone() *HealthRequest {
	return proto.Clone(m).(*HealthRequest)
}

func (m *HealthResponse) Clone() *HealthResponse {
	return proto.Clone(m).(*HealthResponse)
}

func (m *LoginRequest) Clone() *LoginRequest {
	return proto.Clone(m).(*LoginRequest)
}

func (m *LoginResponse) Clone() *LoginResponse {
	return proto.Clone(m).(*LoginResponse)
}

func (m *UserInfoRequest) Clone() *UserInfoRequest {
	return proto.Clone(m).(*UserInfoRequest)
}

func (m *UserInfoSimple) Clone() *UserInfoSimple {
	return proto.Clone(m).(*UserInfoSimple)
}

func (m *UserInfoResponse) Clone() *UserInfoResponse {
	return proto.Clone(m).(*UserInfoResponse)
}

func (m *UpdateInfoRequest) Clone() *UpdateInfoRequest {
	return proto.Clone(m).(*UpdateInfoRequest)
}

func (m *UpdateInfoResponse) Clone() *UpdateInfoResponse {
	return proto.Clone(m).(*UpdateInfoResponse)
}

func (m *ModifyPasswordRequest) Clone() *ModifyPasswordRequest {
	return proto.Clone(m).(*ModifyPasswordRequest)
}

func (m *ModifyPasswordResponse) Clone() *ModifyPasswordResponse {
	return proto.Clone(m).(*ModifyPasswordResponse)
}

func (m *ModelAccount) Clone() *ModelAccount {
	return proto.Clone(m).(*ModelAccount)
}

func (m *ModelNamespace) Clone() *ModelNamespace {
	return proto.Clone(m).(*ModelNamespace)
}

func (m *NamespaceResp) Clone() *NamespaceResp {
	return proto.Clone(m).(*NamespaceResp)
}

func (m *ModelConfig) Clone() *ModelConfig {
	return proto.Clone(m).(*ModelConfig)
}

func (m *ModelConfigRecord) Clone() *ModelConfigRecord {
	return proto.Clone(m).(*ModelConfigRecord)
}

func (m *ConfigResp) Clone() *ConfigResp {
	return proto.Clone(m).(*ConfigResp)
}

func (m *ModelKeyValue) Clone() *ModelKeyValue {
	return proto.Clone(m).(*ModelKeyValue)
}

func (m *KeyValueResp) Clone() *KeyValueResp {
	return proto.Clone(m).(*KeyValueResp)
}

func (m *SaveOrCreateUserRequest) Clone() *SaveOrCreateUserRequest {
	return proto.Clone(m).(*SaveOrCreateUserRequest)
}

func (m *SaveOrCreateUserResponse) Clone() *SaveOrCreateUserResponse {
	return proto.Clone(m).(*SaveOrCreateUserResponse)
}

func (m *UserListItem) Clone() *UserListItem {
	return proto.Clone(m).(*UserListItem)
}

func (m *UserListRequest) Clone() *UserListRequest {
	return proto.Clone(m).(*UserListRequest)
}

func (m *UserListResponse) Clone() *UserListResponse {
	return proto.Clone(m).(*UserListResponse)
}

func (m *SaveNamespaceRequest) Clone() *SaveNamespaceRequest {
	return proto.Clone(m).(*SaveNamespaceRequest)
}

func (m *SaveNamespaceResponse) Clone() *SaveNamespaceResponse {
	return proto.Clone(m).(*SaveNamespaceResponse)
}

func (m *ListNamespaceRequest) Clone() *ListNamespaceRequest {
	return proto.Clone(m).(*ListNamespaceRequest)
}

func (m *ListNamespaceItem) Clone() *ListNamespaceItem {
	return proto.Clone(m).(*ListNamespaceItem)
}

func (m *ListNamespaceResponse) Clone() *ListNamespaceResponse {
	return proto.Clone(m).(*ListNamespaceResponse)
}

func (m *DeleteNamespaceRequest) Clone() *DeleteNamespaceRequest {
	return proto.Clone(m).(*DeleteNamespaceRequest)
}

func (m *DeleteNamespaceResponse) Clone() *DeleteNamespaceResponse {
	return proto.Clone(m).(*DeleteNamespaceResponse)
}

func (m *SaveConfigRequest) Clone() *SaveConfigRequest {
	return proto.Clone(m).(*SaveConfigRequest)
}

func (m *SaveConfigResponse) Clone() *SaveConfigResponse {
	return proto.Clone(m).(*SaveConfigResponse)
}

func (m *DeleteConfigRequest) Clone() *DeleteConfigRequest {
	return proto.Clone(m).(*DeleteConfigRequest)
}

func (m *DeleteConfigResponse) Clone() *DeleteConfigResponse {
	return proto.Clone(m).(*DeleteConfigResponse)
}

func (m *ListConfigRequest) Clone() *ListConfigRequest {
	return proto.Clone(m).(*ListConfigRequest)
}

func (m *ListConfigItem) Clone() *ListConfigItem {
	return proto.Clone(m).(*ListConfigItem)
}

func (m *ListConfigResponse) Clone() *ListConfigResponse {
	return proto.Clone(m).(*ListConfigResponse)
}

func (m *CloneConfigRequest) Clone() *CloneConfigRequest {
	return proto.Clone(m).(*CloneConfigRequest)
}

func (m *CloneConfigResponse) Clone() *CloneConfigResponse {
	return proto.Clone(m).(*CloneConfigResponse)
}

func (m *SaveValueRequest) Clone() *SaveValueRequest {
	return proto.Clone(m).(*SaveValueRequest)
}

func (m *SaveValueResponse) Clone() *SaveValueResponse {
	return proto.Clone(m).(*SaveValueResponse)
}

func (m *ListValueRequest) Clone() *ListValueRequest {
	return proto.Clone(m).(*ListValueRequest)
}

func (m *ListValueResponse) Clone() *ListValueResponse {
	return proto.Clone(m).(*ListValueResponse)
}

func (m *DeleteValueRequest) Clone() *DeleteValueRequest {
	return proto.Clone(m).(*DeleteValueRequest)
}

func (m *DeleteValueResponse) Clone() *DeleteValueResponse {
	return proto.Clone(m).(*DeleteValueResponse)
}

func (m *DisableValueRequest) Clone() *DisableValueRequest {
	return proto.Clone(m).(*DisableValueRequest)
}

func (m *DisableValueResponse) Clone() *DisableValueResponse {
	return proto.Clone(m).(*DisableValueResponse)
}

func (m *UpdateStatusValueRequest) Clone() *UpdateStatusValueRequest {
	return proto.Clone(m).(*UpdateStatusValueRequest)
}

func (m *UpdateStatusValueResponse) Clone() *UpdateStatusValueResponse {
	return proto.Clone(m).(*UpdateStatusValueResponse)
}

func (m *ListAllValueRequest) Clone() *ListAllValueRequest {
	return proto.Clone(m).(*ListAllValueRequest)
}

func (m *ListAllValueResponse) Clone() *ListAllValueResponse {
	return proto.Clone(m).(*ListAllValueResponse)
}

func (m *UserUpdateStatusRequest) Clone() *UserUpdateStatusRequest {
	return proto.Clone(m).(*UserUpdateStatusRequest)
}

func (m *UserUpdateStatusResponse) Clone() *UserUpdateStatusResponse {
	return proto.Clone(m).(*UserUpdateStatusResponse)
}

func (m *UserDeleteRequest) Clone() *UserDeleteRequest {
	return proto.Clone(m).(*UserDeleteRequest)
}

func (m *UserDeleteResponse) Clone() *UserDeleteResponse {
	return proto.Clone(m).(*UserDeleteResponse)
}

func (m *UpdateStatusNamespaceRequest) Clone() *UpdateStatusNamespaceRequest {
	return proto.Clone(m).(*UpdateStatusNamespaceRequest)
}

func (m *UpdateStatusNamespaceResponse) Clone() *UpdateStatusNamespaceResponse {
	return proto.Clone(m).(*UpdateStatusNamespaceResponse)
}

func (m *UpdateStatusConfigRequest) Clone() *UpdateStatusConfigRequest {
	return proto.Clone(m).(*UpdateStatusConfigRequest)
}

func (m *UpdateStatusConfigResponse) Clone() *UpdateStatusConfigResponse {
	return proto.Clone(m).(*UpdateStatusConfigResponse)
}

func (m *SelectorRequest) Clone() *SelectorRequest {
	return proto.Clone(m).(*SelectorRequest)
}

func (m *SelectorItem) Clone() *SelectorItem {
	return proto.Clone(m).(*SelectorItem)
}

func (m *SelectorResponse) Clone() *SelectorResponse {
	return proto.Clone(m).(*SelectorResponse)
}

func (m *ModelAccessKey) Clone() *ModelAccessKey {
	return proto.Clone(m).(*ModelAccessKey)
}

func (m *AccessKeyItem) Clone() *AccessKeyItem {
	return proto.Clone(m).(*AccessKeyItem)
}

func (m *AccessKeyListRequest) Clone() *AccessKeyListRequest {
	return proto.Clone(m).(*AccessKeyListRequest)
}

func (m *AccessKeyListResponse) Clone() *AccessKeyListResponse {
	return proto.Clone(m).(*AccessKeyListResponse)
}

func (m *CreateAccessKeyRequest) Clone() *CreateAccessKeyRequest {
	return proto.Clone(m).(*CreateAccessKeyRequest)
}

func (m *CreateAccessKeyResponse) Clone() *CreateAccessKeyResponse {
	return proto.Clone(m).(*CreateAccessKeyResponse)
}

func (m *UpdateStatusAccessKeyRequest) Clone() *UpdateStatusAccessKeyRequest {
	return proto.Clone(m).(*UpdateStatusAccessKeyRequest)
}

func (m *UpdateStatusAccessKeyResponse) Clone() *UpdateStatusAccessKeyResponse {
	return proto.Clone(m).(*UpdateStatusAccessKeyResponse)
}

func (m *DeleteAccessKeyRequest) Clone() *DeleteAccessKeyRequest {
	return proto.Clone(m).(*DeleteAccessKeyRequest)
}

func (m *DeleteAccessKeyResponse) Clone() *DeleteAccessKeyResponse {
	return proto.Clone(m).(*DeleteAccessKeyResponse)
}

func (m *SetAccessKeyRemarkRequest) Clone() *SetAccessKeyRemarkRequest {
	return proto.Clone(m).(*SetAccessKeyRemarkRequest)
}

func (m *SetAccessKeyRemarkResponse) Clone() *SetAccessKeyRemarkResponse {
	return proto.Clone(m).(*SetAccessKeyRemarkResponse)
}

func (m *ListAllValueByConfigIdRequest) Clone() *ListAllValueByConfigIdRequest {
	return proto.Clone(m).(*ListAllValueByConfigIdRequest)
}

func (m *ListAllValueByConfigIdResponse) Clone() *ListAllValueByConfigIdResponse {
	return proto.Clone(m).(*ListAllValueByConfigIdResponse)
}
