// Code generated by yc@{{.Version}}
package config

import "github.com/juxuny/yc/env"

var Env = struct {
	RpcPort      int    `env:"20443"`
	HttpPort     int    `env:"20080"`
    Prefix       string `env:"/api"`
}{}

func init() {
	env.Init(&Env, true)
}
