// Code generated by yc@{{.CommandLineVersion}}. DO NOT EDIT.
package {{.PackageName}}

import (
    "strings"
)

const Name = "{{.ServiceName}}"
const Level = int64({{.Level}})
const Version = "{{.Version}}"
const ServiceCode = "{{.ServiceCode}}"
var ApiGroupName = strings.ReplaceAll(Name, "_", "-")
