// Code generated by yc. DO NOT EDIT.
package {{.PackageAlias}}

import "google.golang.org/protobuf/proto"
{{range $msg := .Messages}}
func (m *{{$msg.Name}}) Clone() *{{$msg.Name}} {
	return proto.Clone(m).(*{{$msg.Name}})
}
{{end}}
