// Code generated by yc. DO NOT EDIT.
package http

import (
	"context"
	"fmt"
	"github.com/juxuny/yc/log"
	"github.com/juxuny/yc/router"
	{{.PackageAlias}} "{{.GoModuleName}}"
	"{{.GoModuleName}}/config"
	"{{.GoModuleName}}/handler"
	"github.com/juxuny/yc/trace"
	"net/http"
)

func Start(ctx context.Context) {
	trace.InitReqId("http")
	r := router.NewRouter("/api")
	if err := r.Register({{.PackageAlias}}.Name, handler.NewWrapper()); err != nil {
		panic(err)
	}
	finished := make(chan bool, 1)
	go func() {
		if err := http.ListenAndServe(fmt.Sprintf(":%d", config.Env.HttpPort), r); err != nil {
			panic(err)
		}
		finished {{.Lt}}- true
	}()
	select {
	case {{.Lt}}-ctx.Done():
		log.Info("canceled")
		return
	case {{.Lt}}-finished:
		log.Info("http server finished")
	}
}
