// Code generated by yc@{{.Version}}. DO NOT EDIT.
using SQLite;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace {{.CSharpNamespace}}
{
    public static class {{.EnumName}}
    {
        {{range $index, $item := .Fields}}public static int {{$item.FieldName|upperFirst}} = {{$item.Value}};
        {{end}}
    }
}

