// Code generated by yc@{{.Version}}. DO NOT EDIT.
using SQLite;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace {{.CSharperNamespace}}
{
    [Table("{{.TableNameWithoutServicePrefix}}")]
    public class {{.ModelName}}
    {
        public static string GetTableName() {
            return "{{.TableNameWithoutServicePrefix}}";
        }
        public {{.ModelName}}() { }

        {{range $index, $item := .Fields}}{{if $item.HasIndex}}[Indexed("{{$item.FieldName|upperFirst}}", {{$index}})]
        {{end}}{{if $item.HasUnique}}[Unique]
        {{end}}public {{.CSharperDataType}} {{$item.FieldName|upperFirst}} { get; set; }

        {{end}}
    }
}

