// Code generated by yc@{{.Version}}. DO NOT EDIT.
using {{.CSharpBaseNamespace}}.Orm;
using SQLite;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace {{.CSharpModelNamespace}}
{
    [Table("{{.TableNameWithoutServicePrefix}}")]
    public class {{.ModelName}}
    {
        public static class TableDefinition {
            {{range $index, $item := .Fields}}public static Field {{$item.FieldName|upperFirst}} = new Field("{{$item.FieldName|upperFirst}}");
            {{end}}
        }

        public static string GetTableName() {
            return "{{.TableNameWithoutServicePrefix}}";
        }
        public {{.ModelName}}() { }

        {{range $index, $item := .Fields}}{{if $item.HasIndex}}[Indexed("{{$item.FieldName|upperFirst}}", {{$index}})]
        {{end}}{{if $item.HasUnique}}[Unique]
        {{end}}public {{.CSharpDataType}} {{$item.FieldName|upperFirst}} { get; set; }

        {{end}}
    }
}

